#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.6
#  in conjunction with Tcl version 8.6
#    Nov 08, 2020 11:55:04 PM EST  platform: Windows NT

import sys
import tkinter as tk
import Tcl
import mysql.connector

#import Base_support
def create_base():
    # Build componrnts
    _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
    _fgcolor = '#000000'  # X11 color: 'black'
    _compcolor = '#d9d9d9' # X11 color: 'gray85'
    _ana1color = '#d9d9d9' # X11 color: 'gray85'
    _ana2color = '#ececec' # Closest X11 color: 'gray92'

    root.geometry("1173x873+319+95")
    root.minsize(120, 1)
    root.maxsize(1924, 1061)
    root.resizable(1,  1)
    #root.title("New Toplevel")
    root.configure(background="#d9d9d9")
    root.configure(highlightbackground="#d9d9d9")
    root.configure(highlightcolor="black")

    canvas_base = tk.Canvas(root)
    canvas_base.place(relx=0.06, rely=0.126, relheight=0.687
            , relwidth=0.873)
    canvas_base.configure(background="#3e3c55")
    canvas_base.configure(borderwidth="2")
    canvas_base.configure(highlightbackground="#d9d9d9")
    canvas_base.configure(highlightcolor="black")
    canvas_base.configure(insertbackground="black")
    canvas_base.configure(relief="ridge")
    canvas_base.configure(selectbackground="blue")
    canvas_base.configure(selectforeground="white")

    button_Inventory = tk.Button(canvas_base)
    button_Inventory.place(relx=0.0, rely=0.0, height=50, width=341)
    button_Inventory.configure(activebackground="#ececec")
    button_Inventory.configure(activeforeground="#000000")
    button_Inventory.configure(background="#d9d9d9")
    button_Inventory.configure(disabledforeground="#a3a3a3")
    button_Inventory.configure(foreground="#000000")
    button_Inventory.configure(highlightbackground="#d9d9d9")
    button_Inventory.configure(highlightcolor="black")
    button_Inventory.configure(pady="0")
    button_Inventory.configure(relief="ridge")
    button_Inventory.configure(text='''Inventory''')

    button_shoplist = tk.Button(canvas_base)
    button_shoplist.place(relx=0.332, rely=0.0, height=50, width=342)
    button_shoplist.configure(activebackground="#ececec")
    button_shoplist.configure(activeforeground="#000000")
    button_shoplist.configure(background="#d9d9d9")
    button_shoplist.configure(disabledforeground="#a3a3a3")
    button_shoplist.configure(foreground="#000000")
    button_shoplist.configure(highlightbackground="#d9d9d9")
    button_shoplist.configure(highlightcolor="black")
    button_shoplist.configure(pady="0")
    button_shoplist.configure(relief="ridge")
    button_shoplist.configure(text='''Shopping List''')

    button_recipies = tk.Button(canvas_base)
    button_recipies.place(relx=0.664, rely=0.0, height=50, width=341)
    button_recipies.configure(activebackground="#ececec")
    button_recipies.configure(activeforeground="#000000")
    button_recipies.configure(background="#d9d9d9")
    button_recipies.configure(disabledforeground="#a3a3a3")
    button_recipies.configure(foreground="#000000")
    button_recipies.configure(highlightbackground="#d9d9d9")
    button_recipies.configure(highlightcolor="black")
    button_recipies.configure(pady="0")
    button_recipies.configure(relief="ridge")
    button_recipies.configure(text='''Recipies''')

    entry_barcode = tk.Entry(canvas_base)
    entry_barcode.place(relx=0.811, rely=0.933, height=20
            , relwidth=0.082)
    entry_barcode.configure(background="white")
    entry_barcode.configure(disabledforeground="#a3a3a3")
    entry_barcode.configure(font="TkFixedFont")
    entry_barcode.configure(foreground="#000000")
    entry_barcode.configure(highlightbackground="#d9d9d9")
    entry_barcode.configure(highlightcolor="black")
    entry_barcode.configure(insertbackground="black")
    entry_barcode.configure(selectbackground="blue")
    entry_barcode.configure(selectforeground="white")

    button_in = tk.Button(canvas_base)
    button_in.place(relx=0.801, rely=0.917, height=50, width=100)
    button_in.configure(activebackground="#ececec")
    button_in.configure(activeforeground="#000000")
    button_in.configure(background="#36a35c")
    button_in.configure(disabledforeground="#a3a3a3")
    button_in.configure(foreground="#000000")
    button_in.configure(highlightbackground="#d9d9d9")
    button_in.configure(highlightcolor="black")
    button_in.configure(pady="0")
    button_in.configure(text='''Scan In''')

    button_out = tk.Button(canvas_base)
    button_out.place(relx=0.899, rely=0.917, height=50, width=100)
    button_out.configure(activebackground="#ececec")
    button_out.configure(activeforeground="#000000")
    button_out.configure(background="#af0101")
    button_out.configure(disabledforeground="#a3a3a3")
    button_out.configure(foreground="#000000")
    button_out.configure(highlightbackground="#d9d9d9")
    button_out.configure(highlightcolor="black")
    button_out.configure(pady="0")
    button_out.configure(text='''Scan Out''')

    entry_addShopList = tk.Entry(canvas_base)
    entry_addShopList.place(relx=0.039, rely=0.933, height=20
            , relwidth=0.248)
    entry_addShopList.configure(background="white")
    entry_addShopList.configure(disabledforeground="#a3a3a3")
    entry_addShopList.configure(font="TkFixedFont")
    entry_addShopList.configure(foreground="#000000")
    entry_addShopList.configure(highlightbackground="#d9d9d9")
    entry_addShopList.configure(highlightcolor="black")
    entry_addShopList.configure(insertbackground="black")
    entry_addShopList.configure(selectbackground="blue")
    entry_addShopList.configure(selectforeground="white")

    button_addShopList = tk.Button(canvas_base)
    button_addShopList.place(relx=0.303, rely=0.933, height=24
            , width=200)
    button_addShopList.configure(activebackground="#ececec")
    button_addShopList.configure(activeforeground="#000000")
    button_addShopList.configure(background="#d9d9d9")
    button_addShopList.configure(disabledforeground="#a3a3a3")
    button_addShopList.configure(foreground="#000000")
    button_addShopList.configure(highlightbackground="#d9d9d9")
    button_addShopList.configure(highlightcolor="black")
    button_addShopList.configure(pady="0")
    button_addShopList.configure(text='''Add To Shopping List''')
##def vp_start_gui():
#    '''Starting point when module is the main routine.'''
global val, w, root

# make root
root = tk.Tk()
root.title("IOT Pantry System")


create_base()


#top = Toplevel1 (root)
#Base_support.init(root, top)

# Start GUI
root.mainloop()










w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel(root)
    top = tk.Toplevel1(w)
    Base_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None



class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("1173x873+319+95")
        top.minsize(120, 1)
        top.maxsize(1924, 1061)
        top.resizable(1,  1)
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        canvas_base = tk.Canvas(top)
        canvas_base.place(relx=0.06, rely=0.126, relheight=0.687
                , relwidth=0.873)
        canvas_base.configure(background="#3e3c55")
        canvas_base.configure(borderwidth="2")
        canvas_base.configure(highlightbackground="#d9d9d9")
        canvas_base.configure(highlightcolor="black")
        canvas_base.configure(insertbackground="black")
        canvas_base.configure(relief="ridge")
        canvas_base.configure(selectbackground="blue")
        canvas_base.configure(selectforeground="white")

        button_Inventory = tk.Button(canvas_base)
        button_Inventory.place(relx=0.0, rely=0.0, height=50, width=341)
        button_Inventory.configure(activebackground="#ececec")
        button_Inventory.configure(activeforeground="#000000")
        button_Inventory.configure(background="#d9d9d9")
        button_Inventory.configure(disabledforeground="#a3a3a3")
        button_Inventory.configure(foreground="#000000")
        button_Inventory.configure(highlightbackground="#d9d9d9")
        button_Inventory.configure(highlightcolor="black")
        button_Inventory.configure(pady="0")
        button_Inventory.configure(relief="ridge")
        button_Inventory.configure(text='''Inventory''')

        button_shoplist = tk.Button(canvas_base)
        button_shoplist.place(relx=0.332, rely=0.0, height=50, width=342)
        button_shoplist.configure(activebackground="#ececec")
        button_shoplist.configure(activeforeground="#000000")
        button_shoplist.configure(background="#d9d9d9")
        button_shoplist.configure(disabledforeground="#a3a3a3")
        button_shoplist.configure(foreground="#000000")
        button_shoplist.configure(highlightbackground="#d9d9d9")
        button_shoplist.configure(highlightcolor="black")
        button_shoplist.configure(pady="0")
        button_shoplist.configure(relief="ridge")
        button_shoplist.configure(text='''Shopping List''')

        button_recipies = tk.Button(canvas_base)
        button_recipies.place(relx=0.664, rely=0.0, height=50, width=341)
        button_recipies.configure(activebackground="#ececec")
        button_recipies.configure(activeforeground="#000000")
        button_recipies.configure(background="#d9d9d9")
        button_recipies.configure(disabledforeground="#a3a3a3")
        button_recipies.configure(foreground="#000000")
        button_recipies.configure(highlightbackground="#d9d9d9")
        button_recipies.configure(highlightcolor="black")
        button_recipies.configure(pady="0")
        button_recipies.configure(relief="ridge")
        button_recipies.configure(text='''Recipies''')

        entry_barcode = tk.Entry(canvas_base)
        entry_barcode.place(relx=0.811, rely=0.933, height=20
                , relwidth=0.082)
        entry_barcode.configure(background="white")
        entry_barcode.configure(disabledforeground="#a3a3a3")
        entry_barcode.configure(font="TkFixedFont")
        entry_barcode.configure(foreground="#000000")
        entry_barcode.configure(highlightbackground="#d9d9d9")
        entry_barcode.configure(highlightcolor="black")
        entry_barcode.configure(insertbackground="black")
        entry_barcode.configure(selectbackground="blue")
        entry_barcode.configure(selectforeground="white")

        button_in = tk.Button(canvas_base)
        button_in.place(relx=0.801, rely=0.917, height=50, width=100)
        button_in.configure(activebackground="#ececec")
        button_in.configure(activeforeground="#000000")
        button_in.configure(background="#36a35c")
        button_in.configure(disabledforeground="#a3a3a3")
        button_in.configure(foreground="#000000")
        button_in.configure(highlightbackground="#d9d9d9")
        button_in.configure(highlightcolor="black")
        button_in.configure(pady="0")
        button_in.configure(text='''Scan In''')

        button_out = tk.Button(canvas_base)
        button_out.place(relx=0.899, rely=0.917, height=50, width=100)
        button_out.configure(activebackground="#ececec")
        button_out.configure(activeforeground="#000000")
        button_out.configure(background="#af0101")
        button_out.configure(disabledforeground="#a3a3a3")
        button_out.configure(foreground="#000000")
        button_out.configure(highlightbackground="#d9d9d9")
        button_out.configure(highlightcolor="black")
        button_out.configure(pady="0")
        button_out.configure(text='''Scan Out''')

        entry_addShopList = tk.Entry(canvas_base)
        entry_addShopList.place(relx=0.039, rely=0.933, height=20
                , relwidth=0.248)
        entry_addShopList.configure(background="white")
        entry_addShopList.configure(disabledforeground="#a3a3a3")
        entry_addShopList.configure(font="TkFixedFont")
        entry_addShopList.configure(foreground="#000000")
        entry_addShopList.configure(highlightbackground="#d9d9d9")
        entry_addShopList.configure(highlightcolor="black")
        entry_addShopList.configure(insertbackground="black")
        entry_addShopList.configure(selectbackground="blue")
        entry_addShopList.configure(selectforeground="white")

        button_addShopList = tk.Button(canvas_base)
        button_addShopList.place(relx=0.303, rely=0.933, height=24
                , width=200)
        button_addShopList.configure(activebackground="#ececec")
        button_addShopList.configure(activeforeground="#000000")
        button_addShopList.configure(background="#d9d9d9")
        button_addShopList.configure(disabledforeground="#a3a3a3")
        button_addShopList.configure(foreground="#000000")
        button_addShopList.configure(highlightbackground="#d9d9d9")
        button_addShopList.configure(highlightcolor="black")
        button_addShopList.configure(pady="0")
        button_addShopList.configure(text='''Add To Shopping List''')

if __name__ == '__main__':
    vp_start_gui()
