#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.6
#  in conjunction with Tcl version 8.6
#    Nov 12, 2020 08:50:31 PM EST  platform: Windows NT

import sys
import tkinter as tk
import Tcl
import mysql.connector


global val, w, root
# make root
root = tk.Tk()
root.title("IOT Pantry System")




_bgcolor = '#d9d9d9'  # X11 color: 'gray85'
_fgcolor = '#000000'  # X11 color: 'black'
_compcolor = '#d9d9d9' # X11 color: 'gray85'
_ana1color = '#d9d9d9' # X11 color: 'gray85'
_ana2color = '#ececec' # Closest X11 color: 'gray92'

root.geometry("1173x873+319+95")
root.minsize(120, 1)
root.maxsize(1924, 1061)
root.resizable(1,  1)
root.title("New rootlevel")
root.configure(background="#d9d9d9")
root.configure(highlightbackground="#d9d9d9")
root.configure(highlightcolor="black")

canvas_base = tk.Canvas(root)
canvas_base.place(relx=0.06, rely=0.126, relheight=0.687
        , relwidth=0.873)
canvas_base.configure(background="#3e3c55")
canvas_base.configure(borderwidth="2")
canvas_base.configure(cursor="fleur")
canvas_base.configure(highlightbackground="#d9d9d9")
canvas_base.configure(highlightcolor="black")
canvas_base.configure(insertbackground="black")
canvas_base.configure(relief="ridge")
canvas_base.configure(selectbackground="blue")
canvas_base.configure(selectforeground="white")

button_Inventory = tk.Button(canvas_base)
button_Inventory.place(relx=0.0, rely=0.0, height=50, width=341)
button_Inventory.configure(activebackground="#ececec")
button_Inventory.configure(activeforeground="#000000")
button_Inventory.configure(background="#d9d9d9")
button_Inventory.configure(disabledforeground="#a3a3a3")
button_Inventory.configure(foreground="#000000")
button_Inventory.configure(highlightbackground="#d9d9d9")
button_Inventory.configure(highlightcolor="black")
button_Inventory.configure(pady="0")
button_Inventory.configure(relief="ridge")
button_Inventory.configure(text='''Inventory''')

button_shoplist = tk.Button(canvas_base)
button_shoplist.place(relx=0.332, rely=0.0, height=50, width=342)
button_shoplist.configure(activebackground="#ececec")
button_shoplist.configure(activeforeground="#000000")
button_shoplist.configure(background="#d9d9d9")
button_shoplist.configure(disabledforeground="#a3a3a3")
button_shoplist.configure(foreground="#000000")
button_shoplist.configure(highlightbackground="#d9d9d9")
button_shoplist.configure(highlightcolor="black")
button_shoplist.configure(pady="0")
button_shoplist.configure(relief="ridge")
button_shoplist.configure(text='''Shopping List''')

button_recipies = tk.Button(canvas_base)
button_recipies.place(relx=0.664, rely=0.0, height=50, width=341)
button_recipies.configure(activebackground="#ececec")
button_recipies.configure(activeforeground="#000000")
button_recipies.configure(background="#d9d9d9")
button_recipies.configure(disabledforeground="#a3a3a3")
button_recipies.configure(foreground="#000000")
button_recipies.configure(highlightbackground="#d9d9d9")
button_recipies.configure(highlightcolor="black")
button_recipies.configure(pady="0")
button_recipies.configure(relief="ridge")
button_recipies.configure(text='''Recipies''')

entry_barcode = tk.Entry(canvas_base)
entry_barcode.place(relx=0.811, rely=0.933, height=20
        , relwidth=0.082)
entry_barcode.configure(background="white")
entry_barcode.configure(disabledforeground="#a3a3a3")
entry_barcode.configure(font="TkFixedFont")
entry_barcode.configure(foreground="#000000")
entry_barcode.configure(highlightbackground="#d9d9d9")
entry_barcode.configure(highlightcolor="black")
entry_barcode.configure(insertbackground="black")
entry_barcode.configure(selectbackground="blue")
entry_barcode.configure(selectforeground="white")

button_in = tk.Button(canvas_base)
button_in.place(relx=0.801, rely=0.917, height=50, width=100)
button_in.configure(activebackground="#ececec")
button_in.configure(activeforeground="#000000")
button_in.configure(background="#36a35c")
button_in.configure(disabledforeground="#a3a3a3")
button_in.configure(foreground="#000000")
button_in.configure(highlightbackground="#d9d9d9")
button_in.configure(highlightcolor="black")
button_in.configure(pady="0")
button_in.configure(text='''Scan In''')

button_out = tk.Button(canvas_base)
button_out.place(relx=0.899, rely=0.917, height=50, width=100)
button_out.configure(activebackground="#ececec")
button_out.configure(activeforeground="#000000")
button_out.configure(background="#af0101")
button_out.configure(disabledforeground="#a3a3a3")
button_out.configure(foreground="#000000")
button_out.configure(highlightbackground="#d9d9d9")
button_out.configure(highlightcolor="black")
button_out.configure(pady="0")
button_out.configure(text='''Scan Out''')

entry_addShopList = tk.Entry(canvas_base)
entry_addShopList.place(relx=0.039, rely=0.933, height=20
        , relwidth=0.248)
entry_addShopList.configure(background="white")
entry_addShopList.configure(disabledforeground="#a3a3a3")
entry_addShopList.configure(font="TkFixedFont")
entry_addShopList.configure(foreground="#000000")
entry_addShopList.configure(highlightbackground="#d9d9d9")
entry_addShopList.configure(highlightcolor="black")
entry_addShopList.configure(insertbackground="black")
entry_addShopList.configure(selectbackground="blue")
entry_addShopList.configure(selectforeground="white")

button_addShopList = tk.Button(canvas_base)
button_addShopList.place(relx=0.303, rely=0.933, height=24
        , width=200)
button_addShopList.configure(activebackground="#ececec")
button_addShopList.configure(activeforeground="#000000")
button_addShopList.configure(background="#d9d9d9")
button_addShopList.configure(disabledforeground="#a3a3a3")
button_addShopList.configure(foreground="#000000")
button_addShopList.configure(highlightbackground="#d9d9d9")
button_addShopList.configure(highlightcolor="black")
button_addShopList.configure(pady="0")
button_addShopList.configure(text='''Add To Shopping List''')

Frame1 = tk.Frame(canvas_base)
Frame1.place(relx=0.381, rely=0.15, relheight=0.658, relwidth=0.243)

Frame1.configure(relief='groove')
Frame1.configure(borderwidth="2")
Frame1.configure(relief="groove")
Frame1.configure(background="#d9d9d9")

entry_code = tk.Entry(Frame1)
entry_code.place(relx=0.1, rely=0.152, height=20, relwidth=0.803)
entry_code.configure(background="white")
entry_code.configure(cursor="fleur")
entry_code.configure(disabledforeground="#a3a3a3")
entry_code.configure(font="TkFixedFont")
entry_code.configure(foreground="#000000")
entry_code.configure(insertbackground="black")

Entry_prod_name = tk.Entry(Frame1)
Entry_prod_name.place(relx=0.1, rely=0.278, height=20
        , relwidth=0.803)
Entry_prod_name.configure(background="white")
Entry_prod_name.configure(disabledforeground="#a3a3a3")
Entry_prod_name.configure(font="TkFixedFont")
Entry_prod_name.configure(foreground="#000000")
Entry_prod_name.configure(insertbackground="black")

label_code = tk.Label(Frame1)
label_code.place(relx=0.1, rely=0.101, height=21, width=201)
label_code.configure(background="#d9d9d9")
label_code.configure(disabledforeground="#a3a3a3")
label_code.configure(foreground="#000000")
label_code.configure(justify='left')
label_code.configure(text='''Barcode''')

label_prodName = tk.Label(Frame1)
label_prodName.place(relx=0.1, rely=0.228, height=21, width=201)
label_prodName.configure(background="#d9d9d9")
label_prodName.configure(disabledforeground="#a3a3a3")
label_prodName.configure(foreground="#000000")
label_prodName.configure(justify='left')
label_prodName.configure(text='''Product Name''')

Entry_foodGroup = tk.Entry(Frame1)
Entry_foodGroup.place(relx=0.1, rely=0.405, height=20
        , relwidth=0.803)
Entry_foodGroup.configure(background="white")
Entry_foodGroup.configure(disabledforeground="#a3a3a3")
Entry_foodGroup.configure(font="TkFixedFont")
Entry_foodGroup.configure(foreground="#000000")
Entry_foodGroup.configure(insertbackground="black")

Entry_expd = tk.Entry(Frame1)
Entry_expd.place(relx=0.1, rely=0.532, height=20, relwidth=0.803)
Entry_expd.configure(background="white")
Entry_expd.configure(disabledforeground="#a3a3a3")
Entry_expd.configure(font="TkFixedFont")
Entry_expd.configure(foreground="#000000")
Entry_expd.configure(insertbackground="black")

Label_foodGroup = tk.Label(Frame1)
Label_foodGroup.place(relx=0.1, rely=0.354, height=21, width=201)
Label_foodGroup.configure(background="#d9d9d9")
Label_foodGroup.configure(disabledforeground="#a3a3a3")
Label_foodGroup.configure(foreground="#000000")
Label_foodGroup.configure(text='''Food Group''')

Label_enterexp = tk.Label(Frame1)
Label_enterexp.place(relx=0.1, rely=0.481, height=21, width=201)
Label_enterexp.configure(background="#d9d9d9")
Label_enterexp.configure(disabledforeground="#a3a3a3")
Label_enterexp.configure(foreground="#000000")
Label_enterexp.configure(text='''Expiration Date''')

entry_numItems = tk.Entry(Frame1)
entry_numItems.place(relx=0.1, rely=0.658, height=20
        , relwidth=0.803)
entry_numItems.configure(background="white")
entry_numItems.configure(disabledforeground="#a3a3a3")
entry_numItems.configure(font="TkFixedFont")
entry_numItems.configure(foreground="#000000")
entry_numItems.configure(insertbackground="black")

label_numitems = tk.Label(Frame1)
label_numitems.place(relx=0.1, rely=0.608, height=21, width=201)
label_numitems.configure(background="#d9d9d9")
label_numitems.configure(disabledforeground="#a3a3a3")
label_numitems.configure(foreground="#000000")
label_numitems.configure(justify='left')
label_numitems.configure(text='''Quantity''')

button_add = tk.Button(Frame1)
button_add.place(relx=0.201, rely=0.81, height=30, width=150)
button_add.configure(activebackground="#ececec")
button_add.configure(activeforeground="#000000")
button_add.configure(background="#d9d9d9")
button_add.configure(disabledforeground="#a3a3a3")
button_add.configure(foreground="#000000")
button_add.configure(highlightbackground="#d9d9d9")
button_add.configure(highlightcolor="black")
button_add.configure(pady="0")
button_add.configure(text='''Add to Inventory''')


root.mainloop()
