#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.6
#  in conjunction with Tcl version 8.6
#    Nov 09, 2020 12:27:18 AM EST  platform: Windows NT

import sys
import tkinter as tk
import Tcl
import mysql.connector


global val, w, root
# make root
root = tk.Tk()
root.title("IOT Pantry System")


_bgcolor = '#d9d9d9'  # X11 color: 'gray85'
_fgcolor = '#000000'  # X11 color: 'black'
_compcolor = '#d9d9d9' # X11 color: 'gray85'
_ana1color = '#d9d9d9' # X11 color: 'gray85'
_ana2color = '#ececec' # Closest X11 color: 'gray92'
#style = ttk.Style()
#if sys.platform == "win32":
#    style.theme_use('winnative')
#style.configure('.',background=_bgcolor)
#style.configure('.',foreground=_fgcolor)
#style.configure('.',font="TkDefaultFont")
#style.map('.',background=
#    [('selected', _compcolor), ('active',_ana2color)])

root.geometry("1173x873+319+95")
root.minsize(120, 1)
root.maxsize(1924, 1061)
root.resizable(1,  1)
root.title("New rootlevel")
root.configure(background="#d9d9d9")
root.configure(highlightbackground="#d9d9d9")
root.configure(highlightcolor="black")

canvas_base = tk.Canvas(root)
canvas_base.place(relx=0.06, rely=0.126, relheight=0.687
        , relwidth=0.873)
canvas_base.configure(background="#3e3c55")
canvas_base.configure(borderwidth="2")
canvas_base.configure(highlightbackground="#d9d9d9")
canvas_base.configure(highlightcolor="black")
canvas_base.configure(insertbackground="black")
canvas_base.configure(relief="ridge")
canvas_base.configure(selectbackground="blue")
canvas_base.configure(selectforeground="white")

button_Inventory = tk.Button(canvas_base)
button_Inventory.place(relx=0.0, rely=0.0, height=50, width=341)
button_Inventory.configure(activebackground="#ececec")
button_Inventory.configure(activeforeground="#000000")
button_Inventory.configure(background="#d9d9d9")
button_Inventory.configure(disabledforeground="#a3a3a3")
button_Inventory.configure(foreground="#000000")
button_Inventory.configure(highlightbackground="#d9d9d9")
button_Inventory.configure(highlightcolor="black")
button_Inventory.configure(pady="0")
button_Inventory.configure(relief="ridge")
button_Inventory.configure(text='''Inventory''')

button_shoplist = tk.Button(canvas_base)
button_shoplist.place(relx=0.332, rely=0.0, height=50, width=342)
button_shoplist.configure(activebackground="#ececec")
button_shoplist.configure(activeforeground="#000000")
button_shoplist.configure(background="#d9d9d9")
button_shoplist.configure(disabledforeground="#a3a3a3")
button_shoplist.configure(foreground="#000000")
button_shoplist.configure(highlightbackground="#d9d9d9")
button_shoplist.configure(highlightcolor="black")
button_shoplist.configure(pady="0")
button_shoplist.configure(relief="ridge")
button_shoplist.configure(text='''Shopping List''')

button_recipies = tk.Button(canvas_base)
button_recipies.place(relx=0.664, rely=0.0, height=50, width=341)
button_recipies.configure(activebackground="#ececec")
button_recipies.configure(activeforeground="#000000")
button_recipies.configure(background="#d9d9d9")
button_recipies.configure(disabledforeground="#a3a3a3")
button_recipies.configure(foreground="#000000")
button_recipies.configure(highlightbackground="#d9d9d9")
button_recipies.configure(highlightcolor="black")
button_recipies.configure(pady="0")
button_recipies.configure(relief="ridge")
button_recipies.configure(text='''Recipies''')

entry_barcode = tk.Entry(canvas_base)
entry_barcode.place(relx=0.801, rely=0.933, height=20
        , relwidth=0.082)
entry_barcode.configure(background="white")
entry_barcode.configure(disabledforeground="#a3a3a3")
entry_barcode.configure(font="TkFixedFont")
entry_barcode.configure(foreground="#000000")
entry_barcode.configure(highlightbackground="#d9d9d9")
entry_barcode.configure(highlightcolor="black")
entry_barcode.configure(insertbackground="black")
entry_barcode.configure(selectbackground="blue")
entry_barcode.configure(selectforeground="white")

button_in = tk.Button(canvas_base)
button_in.place(relx=0.802, rely=0.917, height=50, width=100)
button_in.configure(activebackground="#ececec")
button_in.configure(activeforeground="#000000")
button_in.configure(background="#36a35c")
button_in.configure(disabledforeground="#a3a3a3")
button_in.configure(foreground="#000000")
button_in.configure(highlightbackground="#d9d9d9")
button_in.configure(highlightcolor="black")
button_in.configure(pady="0")
button_in.configure(text='''Scan In''')

button_out = tk.Button(canvas_base)
button_out.place(relx=0.899, rely=0.917, height=50, width=100)
button_out.configure(activebackground="#ececec")
button_out.configure(activeforeground="#000000")
button_out.configure(background="#af0101")
button_out.configure(disabledforeground="#a3a3a3")
button_out.configure(foreground="#000000")
button_out.configure(highlightbackground="#d9d9d9")
button_out.configure(highlightcolor="black")
button_out.configure(pady="0")
button_out.configure(text='''Scan Out''')

entry_addShopList = tk.Entry(canvas_base)
entry_addShopList.place(relx=0.039, rely=0.933, height=20
        , relwidth=0.248)
entry_addShopList.configure(background="white")
entry_addShopList.configure(disabledforeground="#a3a3a3")
entry_addShopList.configure(font="TkFixedFont")
entry_addShopList.configure(foreground="#000000")
entry_addShopList.configure(highlightbackground="#d9d9d9")
entry_addShopList.configure(highlightcolor="black")
entry_addShopList.configure(insertbackground="black")
entry_addShopList.configure(selectbackground="blue")
entry_addShopList.configure(selectforeground="white")

button_addShopList = tk.Button(canvas_base)
button_addShopList.place(relx=0.303, rely=0.933, height=24
        , width=200)
button_addShopList.configure(activebackground="#ececec")
button_addShopList.configure(activeforeground="#000000")
button_addShopList.configure(background="#d9d9d9")
button_addShopList.configure(disabledforeground="#a3a3a3")
button_addShopList.configure(foreground="#000000")
button_addShopList.configure(highlightbackground="#d9d9d9")
button_addShopList.configure(highlightcolor="black")
button_addShopList.configure(pady="0")
button_addShopList.configure(text='''Add To Shopping List''')

frame_rec_menu = tk.Frame(canvas_base)
frame_rec_menu.place(relx=0.0, rely=0.083, relheight=0.083
        , relwidth=1.0)
frame_rec_menu.configure(relief='groove')
frame_rec_menu.configure(borderwidth="2")
frame_rec_menu.configure(relief="groove")
frame_rec_menu.configure(background="#737373")

#TCombobox1 = ttk.Combobox(frame_rec_menu)
#TCombobox1.place(relx=0.596, rely=0.3, relheight=0.42
#        , relwidth=0.146)
#TCombobox1.configure(textvariable=Recipies_support.combobox)
#TCombobox1.configure(takefocus="")

#TCombobox2 = ttk.Combobox(frame_rec_menu)
#TCombobox2.place(relx=0.752, rely=0.3, relheight=0.42
#        , relwidth=0.142)
#TCombobox2.configure(textvariable=Recipies_support.combobox)
#TCombobox2.configure(takefocus="")

Button1 = tk.Button(frame_rec_menu)
Button1.place(relx=0.908, rely=0.3, height=24, width=75)
Button1.configure(activebackground="#ececec")
Button1.configure(activeforeground="#000000")
Button1.configure(background="#d9d9d9")
Button1.configure(disabledforeground="#a3a3a3")
Button1.configure(foreground="#000000")
Button1.configure(highlightbackground="#d9d9d9")
Button1.configure(highlightcolor="black")
Button1.configure(pady="0")
Button1.configure(text='''Filter''')

frame_rec_main = tk.Frame(canvas_base)
frame_rec_main.place(relx=0.0, rely=0.167, relheight=0.75
        , relwidth=1.0)
frame_rec_main.configure(relief='groove')
frame_rec_main.configure(borderwidth="2")
frame_rec_main.configure(relief="groove")
frame_rec_main.configure(background="#585670")

label_rec_name = tk.Label(frame_rec_main)
label_rec_name.place(relx=0.186, rely=0.111, height=30, width=352)
label_rec_name.configure(background="#939393")
label_rec_name.configure(disabledforeground="#a3a3a3")
label_rec_name.configure(foreground="#000000")
label_rec_name.configure(text='''Name''')

label_rec_time = tk.Label(frame_rec_main)
label_rec_time.place(relx=0.586, rely=0.111, height=30, width=150)
label_rec_time.configure(background="#939393")
label_rec_time.configure(disabledforeground="#a3a3a3")
label_rec_time.configure(foreground="#000000")
label_rec_time.configure(text='''Time''')

label_rec_timeDate = tk.Label(frame_rec_main)
label_rec_timeDate.place(relx=0.586, rely=0.222, height=30
        , width=150)
label_rec_timeDate.configure(background="#d9d9d9")
label_rec_timeDate.configure(disabledforeground="#a3a3a3")
label_rec_timeDate.configure(foreground="#000000")
label_rec_timeDate.configure(text='''X''')

button_rec_nameData = tk.Button(frame_rec_main)
button_rec_nameData.place(relx=0.186, rely=0.222, height=30
        , width=350)
button_rec_nameData.configure(activebackground="#ececec")
button_rec_nameData.configure(activeforeground="#000000")
button_rec_nameData.configure(background="#d9d9d9")
button_rec_nameData.configure(cursor="fleur")
button_rec_nameData.configure(disabledforeground="#a3a3a3")
button_rec_nameData.configure(foreground="#000000")
button_rec_nameData.configure(highlightbackground="#d9d9d9")
button_rec_nameData.configure(highlightcolor="black")
button_rec_nameData.configure(pady="0")
button_rec_nameData.configure(relief="flat")
button_rec_nameData.configure(text='''X''')

root.mainloop()
