#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.6
#  in conjunction with Tcl version 8.6
#    Nov 18, 2020 11:05:16 PM EST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import DeletePopup_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    root = rootlevel1 (root)
    DeletePopup_support.init(root, root)
    root.mainloop()

w = None
def create_rootlevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_rootlevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.rootlevel (root)
    root = rootlevel1 (w)
    DeletePopup_support.init(w, root, *args, **kwargs)
    return (w, root)

def destroy_rootlevel1():
    global w
    w.destroy()
    w = None

class rootlevel1:
    def __init__(self, root=None):
        '''This class configures and populates the rootlevel window.
           root is the rootlevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        root.geometry("1173x873+302+80")
        root.minsize(120, 1)
        root.maxsize(1924, 1061)
        root.resizable(1,  1)
        root.title("New rootlevel")
        root.configure(background="#d9d9d9")
        root.configure(highlightbackground="#d9d9d9")
        root.configure(highlightcolor="black")

        canvas_base = tk.Canvas(root)
        canvas_base.place(relx=0.06, rely=0.126, relheight=0.687
                , relwidth=0.873)
        canvas_base.configure(background="#3e3c55")
        canvas_base.configure(borderwidth="2")
        canvas_base.configure(highlightbackground="#d9d9d9")
        canvas_base.configure(highlightcolor="black")
        canvas_base.configure(insertbackground="black")
        canvas_base.configure(relief="ridge")
        canvas_base.configure(selectbackground="blue")
        canvas_base.configure(selectforeground="white")

        button_Inventory = tk.Button(canvas_base)
        button_Inventory.place(relx=0.0, rely=0.0, height=50, width=341)
        button_Inventory.configure(activebackground="#ececec")
        button_Inventory.configure(activeforeground="#000000")
        button_Inventory.configure(background="#d9d9d9")
        button_Inventory.configure(disabledforeground="#a3a3a3")
        button_Inventory.configure(foreground="#000000")
        button_Inventory.configure(highlightbackground="#d9d9d9")
        button_Inventory.configure(highlightcolor="black")
        button_Inventory.configure(pady="0")
        button_Inventory.configure(relief="ridge")
        button_Inventory.configure(text='''Inventory''')

        button_shoplist = tk.Button(canvas_base)
        button_shoplist.place(relx=0.332, rely=0.0, height=50, width=342)
        button_shoplist.configure(activebackground="#ececec")
        button_shoplist.configure(activeforeground="#000000")
        button_shoplist.configure(background="#d9d9d9")
        button_shoplist.configure(disabledforeground="#a3a3a3")
        button_shoplist.configure(foreground="#000000")
        button_shoplist.configure(highlightbackground="#d9d9d9")
        button_shoplist.configure(highlightcolor="black")
        button_shoplist.configure(pady="0")
        button_shoplist.configure(relief="ridge")
        button_shoplist.configure(text='''Shopping List''')

        button_recipies = tk.Button(canvas_base)
        button_recipies.place(relx=0.664, rely=0.0, height=50, width=341)
        button_recipies.configure(activebackground="#ececec")
        button_recipies.configure(activeforeground="#000000")
        button_recipies.configure(background="#d9d9d9")
        button_recipies.configure(disabledforeground="#a3a3a3")
        button_recipies.configure(foreground="#000000")
        button_recipies.configure(highlightbackground="#d9d9d9")
        button_recipies.configure(highlightcolor="black")
        button_recipies.configure(pady="0")
        button_recipies.configure(relief="ridge")
        button_recipies.configure(text='''Recipies''')

        entry_barcode = tk.Entry(canvas_base)
        entry_barcode.place(relx=0.811, rely=0.933, height=20
                , relwidth=0.082)
        entry_barcode.configure(background="white")
        entry_barcode.configure(disabledforeground="#a3a3a3")
        entry_barcode.configure(font="TkFixedFont")
        entry_barcode.configure(foreground="#000000")
        entry_barcode.configure(highlightbackground="#d9d9d9")
        entry_barcode.configure(highlightcolor="black")
        entry_barcode.configure(insertbackground="black")
        entry_barcode.configure(selectbackground="blue")
        entry_barcode.configure(selectforeground="white")

        button_in = tk.Button(canvas_base)
        button_in.place(relx=0.801, rely=0.917, height=50, width=100)
        button_in.configure(activebackground="#ececec")
        button_in.configure(activeforeground="#000000")
        button_in.configure(background="#36a35c")
        button_in.configure(disabledforeground="#a3a3a3")
        button_in.configure(foreground="#000000")
        button_in.configure(highlightbackground="#d9d9d9")
        button_in.configure(highlightcolor="black")
        button_in.configure(pady="0")
        button_in.configure(text='''Scan In''')

        button_out = tk.Button(canvas_base)
        button_out.place(relx=0.899, rely=0.917, height=50, width=100)
        button_out.configure(activebackground="#ececec")
        button_out.configure(activeforeground="#000000")
        button_out.configure(background="#af0101")
        button_out.configure(disabledforeground="#a3a3a3")
        button_out.configure(foreground="#000000")
        button_out.configure(highlightbackground="#d9d9d9")
        button_out.configure(highlightcolor="black")
        button_out.configure(pady="0")
        button_out.configure(text='''Scan Out''')

        entry_addShopList = tk.Entry(canvas_base)
        entry_addShopList.place(relx=0.039, rely=0.933, height=20
                , relwidth=0.248)
        entry_addShopList.configure(background="white")
        entry_addShopList.configure(disabledforeground="#a3a3a3")
        entry_addShopList.configure(font="TkFixedFont")
        entry_addShopList.configure(foreground="#000000")
        entry_addShopList.configure(highlightbackground="#d9d9d9")
        entry_addShopList.configure(highlightcolor="black")
        entry_addShopList.configure(insertbackground="black")
        entry_addShopList.configure(selectbackground="blue")
        entry_addShopList.configure(selectforeground="white")

        button_addShopList = tk.Button(canvas_base)
        button_addShopList.place(relx=0.303, rely=0.933, height=24
                , width=200)
        button_addShopList.configure(activebackground="#ececec")
        button_addShopList.configure(activeforeground="#000000")
        button_addShopList.configure(background="#d9d9d9")
        button_addShopList.configure(disabledforeground="#a3a3a3")
        button_addShopList.configure(foreground="#000000")
        button_addShopList.configure(highlightbackground="#d9d9d9")
        button_addShopList.configure(highlightcolor="black")
        button_addShopList.configure(pady="0")
        button_addShopList.configure(text='''Add To Shopping List''')

        Frame1 = tk.Frame(canvas_base)
        Frame1.place(relx=0.371, rely=0.183, relheight=0.542
                , relwidth=0.271)
        Frame1.configure(relief='groove')
        Frame1.configure(borderwidth="2")
        Frame1.configure(relief="groove")
        Frame1.configure(background="#d9d9d9")
        Frame1.configure(cursor="fleur")
        Frame1.configure(highlightbackground="#d9d9d9")
        Frame1.configure(highlightcolor="black")

        button_delete = tk.Button(Frame1)
        button_delete.place(relx=0.181, rely=0.831, height=24, width=175)
        button_delete.configure(activebackground="#ececec")
        button_delete.configure(activeforeground="#000000")
        button_delete.configure(background="#d9d9d9")
        button_delete.configure(disabledforeground="#a3a3a3")
        button_delete.configure(foreground="#000000")
        button_delete.configure(highlightbackground="#d9d9d9")
        button_delete.configure(highlightcolor="black")
        button_delete.configure(pady="0")
        button_delete.configure(text='''Remove Item From Inventory''')

        label_delName = tk.Label(Frame1)
        label_delName.place(relx=0.144, rely=0.154, height=21, width=200)
        label_delName.configure(activebackground="#f9f9f9")
        label_delName.configure(activeforeground="black")
        label_delName.configure(background="#d9d9d9")
        label_delName.configure(disabledforeground="#a3a3a3")
        label_delName.configure(foreground="#000000")
        label_delName.configure(highlightbackground="#d9d9d9")
        label_delName.configure(highlightcolor="black")
        label_delName.configure(justify='left')
        label_delName.configure(text='''Name''')

        entry_numDelete = tk.Entry(Frame1)
        entry_numDelete.place(relx=0.578, rely=0.646, height=20
                , relwidth=0.159)
        entry_numDelete.configure(background="white")
        entry_numDelete.configure(disabledforeground="#a3a3a3")
        entry_numDelete.configure(font="TkFixedFont")
        entry_numDelete.configure(foreground="#000000")
        entry_numDelete.configure(highlightbackground="#d9d9d9")
        entry_numDelete.configure(highlightcolor="black")
        entry_numDelete.configure(insertbackground="black")
        entry_numDelete.configure(selectbackground="blue")
        entry_numDelete.configure(selectforeground="white")

        label_barDelete = tk.Label(Frame1)
        label_barDelete.place(relx=0.144, rely=0.215, height=21, width=200)
        label_barDelete.configure(activebackground="#f9f9f9")
        label_barDelete.configure(activeforeground="black")
        label_barDelete.configure(background="#d9d9d9")
        label_barDelete.configure(disabledforeground="#a3a3a3")
        label_barDelete.configure(foreground="#000000")
        label_barDelete.configure(highlightbackground="#d9d9d9")
        label_barDelete.configure(highlightcolor="black")
        label_barDelete.configure(justify='left')
        label_barDelete.configure(text='''Barcode''')

        label_expDel = tk.Label(Frame1)
        label_expDel.place(relx=0.144, rely=0.277, height=21, width=200)
        label_expDel.configure(activebackground="#f9f9f9")
        label_expDel.configure(activeforeground="black")
        label_expDel.configure(background="#d9d9d9")
        label_expDel.configure(disabledforeground="#a3a3a3")
        label_expDel.configure(foreground="#000000")
        label_expDel.configure(highlightbackground="#d9d9d9")
        label_expDel.configure(highlightcolor="black")
        label_expDel.configure(justify='left')
        label_expDel.configure(text='''Expiration Date''')

        label_entDate = tk.Label(Frame1)
        label_entDate.place(relx=0.144, rely=0.338, height=21, width=200)
        label_entDate.configure(activebackground="#f9f9f9")
        label_entDate.configure(activeforeground="black")
        label_entDate.configure(background="#d9d9d9")
        label_entDate.configure(disabledforeground="#a3a3a3")
        label_entDate.configure(foreground="#000000")
        label_entDate.configure(highlightbackground="#d9d9d9")
        label_entDate.configure(highlightcolor="black")
        label_entDate.configure(justify='left')
        label_entDate.configure(text='''Entry Date''')

        label_curNum = tk.Label(Frame1)
        label_curNum.place(relx=0.144, rely=0.4, height=21, width=200)
        label_curNum.configure(activebackground="#f9f9f9")
        label_curNum.configure(activeforeground="black")
        label_curNum.configure(background="#d9d9d9")
        label_curNum.configure(cursor="fleur")
        label_curNum.configure(disabledforeground="#a3a3a3")
        label_curNum.configure(foreground="#000000")
        label_curNum.configure(highlightbackground="#d9d9d9")
        label_curNum.configure(highlightcolor="black")
        label_curNum.configure(justify='left')
        label_curNum.configure(text='''Current Quantity''')

        label_numDel = tk.Label(Frame1)
        label_numDel.place(relx=0.144, rely=0.646, height=21, width=114)
        label_numDel.configure(activebackground="#f9f9f9")
        label_numDel.configure(activeforeground="black")
        label_numDel.configure(background="#d9d9d9")
        label_numDel.configure(disabledforeground="#a3a3a3")
        label_numDel.configure(foreground="#000000")
        label_numDel.configure(highlightbackground="#d9d9d9")
        label_numDel.configure(highlightcolor="black")
        label_numDel.configure(text='''Amount To Remove:''')

        button_closeDel = tk.Button(Frame1)
        button_closeDel.place(relx=0.884, rely=0.031, height=25, width=25)
        button_closeDel.configure(activebackground="#ececec")
        button_closeDel.configure(activeforeground="#000000")
        button_closeDel.configure(background="#acacac")
        button_closeDel.configure(disabledforeground="#a3a3a3")
        button_closeDel.configure(foreground="#000000")
        button_closeDel.configure(highlightbackground="#d9d9d9")
        button_closeDel.configure(highlightcolor="black")
        button_closeDel.configure(pady="0")
        button_closeDel.configure(text='''X''')

        label_userInst = tk.Label(Frame1)
        label_userInst.place(relx=0.144, rely=0.062, height=21, width=200)
        label_userInst.configure(background="#d9d9d9")
        label_userInst.configure(disabledforeground="#a3a3a3")
        label_userInst.configure(foreground="#000000")
        label_userInst.configure(text='''Scan An Item''')

if __name__ == '__main__':
    vp_start_gui()
