#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.6
#  in conjunction with Tcl version 8.6
#    Nov 12, 2020 08:50:31 PM EST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import EntryScreen_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    EntryScreen_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    EntryScreen_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("1173x873+319+95")
        top.minsize(120, 1)
        top.maxsize(1924, 1061)
        top.resizable(1,  1)
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.canvas_base = tk.Canvas(top)
        self.canvas_base.place(relx=0.06, rely=0.126, relheight=0.687
                , relwidth=0.873)
        self.canvas_base.configure(background="#3e3c55")
        self.canvas_base.configure(borderwidth="2")
        self.canvas_base.configure(cursor="fleur")
        self.canvas_base.configure(highlightbackground="#d9d9d9")
        self.canvas_base.configure(highlightcolor="black")
        self.canvas_base.configure(insertbackground="black")
        self.canvas_base.configure(relief="ridge")
        self.canvas_base.configure(selectbackground="blue")
        self.canvas_base.configure(selectforeground="white")

        self.button_Inventory = tk.Button(self.canvas_base)
        self.button_Inventory.place(relx=0.0, rely=0.0, height=50, width=341)
        self.button_Inventory.configure(activebackground="#ececec")
        self.button_Inventory.configure(activeforeground="#000000")
        self.button_Inventory.configure(background="#d9d9d9")
        self.button_Inventory.configure(disabledforeground="#a3a3a3")
        self.button_Inventory.configure(foreground="#000000")
        self.button_Inventory.configure(highlightbackground="#d9d9d9")
        self.button_Inventory.configure(highlightcolor="black")
        self.button_Inventory.configure(pady="0")
        self.button_Inventory.configure(relief="ridge")
        self.button_Inventory.configure(text='''Inventory''')

        self.button_shoplist = tk.Button(self.canvas_base)
        self.button_shoplist.place(relx=0.332, rely=0.0, height=50, width=342)
        self.button_shoplist.configure(activebackground="#ececec")
        self.button_shoplist.configure(activeforeground="#000000")
        self.button_shoplist.configure(background="#d9d9d9")
        self.button_shoplist.configure(disabledforeground="#a3a3a3")
        self.button_shoplist.configure(foreground="#000000")
        self.button_shoplist.configure(highlightbackground="#d9d9d9")
        self.button_shoplist.configure(highlightcolor="black")
        self.button_shoplist.configure(pady="0")
        self.button_shoplist.configure(relief="ridge")
        self.button_shoplist.configure(text='''Shopping List''')

        self.button_recipies = tk.Button(self.canvas_base)
        self.button_recipies.place(relx=0.664, rely=0.0, height=50, width=341)
        self.button_recipies.configure(activebackground="#ececec")
        self.button_recipies.configure(activeforeground="#000000")
        self.button_recipies.configure(background="#d9d9d9")
        self.button_recipies.configure(disabledforeground="#a3a3a3")
        self.button_recipies.configure(foreground="#000000")
        self.button_recipies.configure(highlightbackground="#d9d9d9")
        self.button_recipies.configure(highlightcolor="black")
        self.button_recipies.configure(pady="0")
        self.button_recipies.configure(relief="ridge")
        self.button_recipies.configure(text='''Recipies''')

        self.entry_barcode = tk.Entry(self.canvas_base)
        self.entry_barcode.place(relx=0.811, rely=0.933, height=20
                , relwidth=0.082)
        self.entry_barcode.configure(background="white")
        self.entry_barcode.configure(disabledforeground="#a3a3a3")
        self.entry_barcode.configure(font="TkFixedFont")
        self.entry_barcode.configure(foreground="#000000")
        self.entry_barcode.configure(highlightbackground="#d9d9d9")
        self.entry_barcode.configure(highlightcolor="black")
        self.entry_barcode.configure(insertbackground="black")
        self.entry_barcode.configure(selectbackground="blue")
        self.entry_barcode.configure(selectforeground="white")

        self.button_in = tk.Button(self.canvas_base)
        self.button_in.place(relx=0.801, rely=0.917, height=50, width=100)
        self.button_in.configure(activebackground="#ececec")
        self.button_in.configure(activeforeground="#000000")
        self.button_in.configure(background="#36a35c")
        self.button_in.configure(disabledforeground="#a3a3a3")
        self.button_in.configure(foreground="#000000")
        self.button_in.configure(highlightbackground="#d9d9d9")
        self.button_in.configure(highlightcolor="black")
        self.button_in.configure(pady="0")
        self.button_in.configure(text='''Scan In''')

        self.button_out = tk.Button(self.canvas_base)
        self.button_out.place(relx=0.899, rely=0.917, height=50, width=100)
        self.button_out.configure(activebackground="#ececec")
        self.button_out.configure(activeforeground="#000000")
        self.button_out.configure(background="#af0101")
        self.button_out.configure(disabledforeground="#a3a3a3")
        self.button_out.configure(foreground="#000000")
        self.button_out.configure(highlightbackground="#d9d9d9")
        self.button_out.configure(highlightcolor="black")
        self.button_out.configure(pady="0")
        self.button_out.configure(text='''Scan Out''')

        self.entry_addShopList = tk.Entry(self.canvas_base)
        self.entry_addShopList.place(relx=0.039, rely=0.933, height=20
                , relwidth=0.248)
        self.entry_addShopList.configure(background="white")
        self.entry_addShopList.configure(disabledforeground="#a3a3a3")
        self.entry_addShopList.configure(font="TkFixedFont")
        self.entry_addShopList.configure(foreground="#000000")
        self.entry_addShopList.configure(highlightbackground="#d9d9d9")
        self.entry_addShopList.configure(highlightcolor="black")
        self.entry_addShopList.configure(insertbackground="black")
        self.entry_addShopList.configure(selectbackground="blue")
        self.entry_addShopList.configure(selectforeground="white")

        self.button_addShopList = tk.Button(self.canvas_base)
        self.button_addShopList.place(relx=0.303, rely=0.933, height=24
                , width=200)
        self.button_addShopList.configure(activebackground="#ececec")
        self.button_addShopList.configure(activeforeground="#000000")
        self.button_addShopList.configure(background="#d9d9d9")
        self.button_addShopList.configure(disabledforeground="#a3a3a3")
        self.button_addShopList.configure(foreground="#000000")
        self.button_addShopList.configure(highlightbackground="#d9d9d9")
        self.button_addShopList.configure(highlightcolor="black")
        self.button_addShopList.configure(pady="0")
        self.button_addShopList.configure(text='''Add To Shopping List''')

        self.Frame1 = tk.Frame(self.canvas_base)
        self.Frame1.place(relx=0.381, rely=0.15, relheight=0.658, relwidth=0.243)

        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#d9d9d9")

        self.entry_code = tk.Entry(self.Frame1)
        self.entry_code.place(relx=0.1, rely=0.152, height=20, relwidth=0.803)
        self.entry_code.configure(background="white")
        self.entry_code.configure(cursor="fleur")
        self.entry_code.configure(disabledforeground="#a3a3a3")
        self.entry_code.configure(font="TkFixedFont")
        self.entry_code.configure(foreground="#000000")
        self.entry_code.configure(insertbackground="black")

        self.Entry_prod_name = tk.Entry(self.Frame1)
        self.Entry_prod_name.place(relx=0.1, rely=0.278, height=20
                , relwidth=0.803)
        self.Entry_prod_name.configure(background="white")
        self.Entry_prod_name.configure(disabledforeground="#a3a3a3")
        self.Entry_prod_name.configure(font="TkFixedFont")
        self.Entry_prod_name.configure(foreground="#000000")
        self.Entry_prod_name.configure(insertbackground="black")

        self.label_code = tk.Label(self.Frame1)
        self.label_code.place(relx=0.1, rely=0.101, height=21, width=201)
        self.label_code.configure(background="#d9d9d9")
        self.label_code.configure(disabledforeground="#a3a3a3")
        self.label_code.configure(foreground="#000000")
        self.label_code.configure(justify='left')
        self.label_code.configure(text='''Barcode''')

        self.label_prodName = tk.Label(self.Frame1)
        self.label_prodName.place(relx=0.1, rely=0.228, height=21, width=201)
        self.label_prodName.configure(background="#d9d9d9")
        self.label_prodName.configure(disabledforeground="#a3a3a3")
        self.label_prodName.configure(foreground="#000000")
        self.label_prodName.configure(justify='left')
        self.label_prodName.configure(text='''Product Name''')

        self.Entry_foodGroup = tk.Entry(self.Frame1)
        self.Entry_foodGroup.place(relx=0.1, rely=0.405, height=20
                , relwidth=0.803)
        self.Entry_foodGroup.configure(background="white")
        self.Entry_foodGroup.configure(disabledforeground="#a3a3a3")
        self.Entry_foodGroup.configure(font="TkFixedFont")
        self.Entry_foodGroup.configure(foreground="#000000")
        self.Entry_foodGroup.configure(insertbackground="black")

        self.Entry_expd = tk.Entry(self.Frame1)
        self.Entry_expd.place(relx=0.1, rely=0.532, height=20, relwidth=0.803)
        self.Entry_expd.configure(background="white")
        self.Entry_expd.configure(disabledforeground="#a3a3a3")
        self.Entry_expd.configure(font="TkFixedFont")
        self.Entry_expd.configure(foreground="#000000")
        self.Entry_expd.configure(insertbackground="black")

        self.Label_foodGroup = tk.Label(self.Frame1)
        self.Label_foodGroup.place(relx=0.1, rely=0.354, height=21, width=201)
        self.Label_foodGroup.configure(background="#d9d9d9")
        self.Label_foodGroup.configure(disabledforeground="#a3a3a3")
        self.Label_foodGroup.configure(foreground="#000000")
        self.Label_foodGroup.configure(text='''Food Group''')

        self.Label_enterexp = tk.Label(self.Frame1)
        self.Label_enterexp.place(relx=0.1, rely=0.481, height=21, width=201)
        self.Label_enterexp.configure(background="#d9d9d9")
        self.Label_enterexp.configure(disabledforeground="#a3a3a3")
        self.Label_enterexp.configure(foreground="#000000")
        self.Label_enterexp.configure(text='''Expiration Date''')

        self.entry_numItems = tk.Entry(self.Frame1)
        self.entry_numItems.place(relx=0.1, rely=0.658, height=20
                , relwidth=0.803)
        self.entry_numItems.configure(background="white")
        self.entry_numItems.configure(disabledforeground="#a3a3a3")
        self.entry_numItems.configure(font="TkFixedFont")
        self.entry_numItems.configure(foreground="#000000")
        self.entry_numItems.configure(insertbackground="black")

        self.label_numitems = tk.Label(self.Frame1)
        self.label_numitems.place(relx=0.1, rely=0.608, height=21, width=201)
        self.label_numitems.configure(background="#d9d9d9")
        self.label_numitems.configure(disabledforeground="#a3a3a3")
        self.label_numitems.configure(foreground="#000000")
        self.label_numitems.configure(justify='left')
        self.label_numitems.configure(text='''Quantity''')

        self.button_add = tk.Button(self.Frame1)
        self.button_add.place(relx=0.201, rely=0.81, height=30, width=150)
        self.button_add.configure(activebackground="#ececec")
        self.button_add.configure(activeforeground="#000000")
        self.button_add.configure(background="#d9d9d9")
        self.button_add.configure(disabledforeground="#a3a3a3")
        self.button_add.configure(foreground="#000000")
        self.button_add.configure(highlightbackground="#d9d9d9")
        self.button_add.configure(highlightcolor="black")
        self.button_add.configure(pady="0")
        self.button_add.configure(text='''Add to Inventory''')

if __name__ == '__main__':
    vp_start_gui()





