#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.6
#  in conjunction with Tcl version 8.6
#    Nov 21, 2020 03:53:25 PM EST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import Inventory_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    Inventory_support.set_Tk_var()
    root = rootlevel1 (root)
    Inventory_support.init(root, root)
    root.mainloop()

w = None
def create_rootlevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_rootlevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.rootlevel (root)
    Inventory_support.set_Tk_var()
    root = rootlevel1 (w)
    Inventory_support.init(w, root, *args, **kwargs)
    return (w, root)

def destroy_rootlevel1():
    global w
    w.destroy()
    w = None

class rootlevel1:
    def __init__(self, root=None):
        '''This class configures and populates the rootlevel window.
           root is the rootlevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        style = ttk.Style()
        if sys.platform == "win32":
            style.theme_use('winnative')
        style.configure('.',background=_bgcolor)
        style.configure('.',foreground=_fgcolor)
        style.configure('.',font="TkDefaultFont")
        style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        root.geometry("1173x873+319+95")
        root.minsize(120, 1)
        root.maxsize(1924, 1061)
        root.resizable(1,  1)
        root.title("New rootlevel")
        root.configure(background="#d9d9d9")
        root.configure(highlightbackground="#d9d9d9")
        root.configure(highlightcolor="black")

        canvas_base = tk.Canvas(root)
        canvas_base.place(relx=0.06, rely=0.126, relheight=0.687
                , relwidth=0.873)
        canvas_base.configure(background="#3e3c55")
        canvas_base.configure(borderwidth="2")
        canvas_base.configure(highlightbackground="#d9d9d9")
        canvas_base.configure(highlightcolor="black")
        canvas_base.configure(insertbackground="black")
        canvas_base.configure(relief="ridge")
        canvas_base.configure(selectbackground="blue")
        canvas_base.configure(selectforeground="white")

        button_Inventory = tk.Button(canvas_base)
        button_Inventory.place(relx=0.0, rely=0.0, height=50, width=341)
        button_Inventory.configure(activebackground="#ececec")
        button_Inventory.configure(activeforeground="#000000")
        button_Inventory.configure(background="#d9d9d9")
        button_Inventory.configure(disabledforeground="#a3a3a3")
        button_Inventory.configure(foreground="#000000")
        button_Inventory.configure(highlightbackground="#d9d9d9")
        button_Inventory.configure(highlightcolor="black")
        button_Inventory.configure(pady="0")
        button_Inventory.configure(relief="ridge")
        button_Inventory.configure(text='''Inventory''')

        button_shoplist = tk.Button(canvas_base)
        button_shoplist.place(relx=0.332, rely=0.0, height=50, width=342)
        button_shoplist.configure(activebackground="#ececec")
        button_shoplist.configure(activeforeground="#000000")
        button_shoplist.configure(background="#d9d9d9")
        button_shoplist.configure(disabledforeground="#a3a3a3")
        button_shoplist.configure(foreground="#000000")
        button_shoplist.configure(highlightbackground="#d9d9d9")
        button_shoplist.configure(highlightcolor="black")
        button_shoplist.configure(pady="0")
        button_shoplist.configure(relief="ridge")
        button_shoplist.configure(text='''Shopping List''')

        button_recipies = tk.Button(canvas_base)
        button_recipies.place(relx=0.664, rely=0.0, height=50, width=341)
        button_recipies.configure(activebackground="#ececec")
        button_recipies.configure(activeforeground="#000000")
        button_recipies.configure(background="#d9d9d9")
        button_recipies.configure(disabledforeground="#a3a3a3")
        button_recipies.configure(foreground="#000000")
        button_recipies.configure(highlightbackground="#d9d9d9")
        button_recipies.configure(highlightcolor="black")
        button_recipies.configure(pady="0")
        button_recipies.configure(relief="ridge")
        button_recipies.configure(text='''Recipies''')

        entry_barcode = tk.Entry(canvas_base)
        entry_barcode.place(relx=0.811, rely=0.933, height=20
                , relwidth=0.082)
        entry_barcode.configure(background="white")
        entry_barcode.configure(disabledforeground="#a3a3a3")
        entry_barcode.configure(font="TkFixedFont")
        entry_barcode.configure(foreground="#000000")
        entry_barcode.configure(highlightbackground="#d9d9d9")
        entry_barcode.configure(highlightcolor="black")
        entry_barcode.configure(insertbackground="black")
        entry_barcode.configure(selectbackground="blue")
        entry_barcode.configure(selectforeground="white")

        button_in = tk.Button(canvas_base)
        button_in.place(relx=0.802, rely=0.917, height=50, width=100)
        button_in.configure(activebackground="#ececec")
        button_in.configure(activeforeground="#000000")
        button_in.configure(background="#36a35c")
        button_in.configure(disabledforeground="#a3a3a3")
        button_in.configure(foreground="#000000")
        button_in.configure(highlightbackground="#d9d9d9")
        button_in.configure(highlightcolor="black")
        button_in.configure(pady="0")
        button_in.configure(relief="ridge")
        button_in.configure(text='''Scan In''')

        button_out = tk.Button(canvas_base)
        button_out.place(relx=0.9, rely=0.917, height=50, width=100)
        button_out.configure(activebackground="#ececec")
        button_out.configure(activeforeground="#000000")
        button_out.configure(background="#af0101")
        button_out.configure(disabledforeground="#a3a3a3")
        button_out.configure(foreground="#000000")
        button_out.configure(highlightbackground="#d9d9d9")
        button_out.configure(highlightcolor="black")
        button_out.configure(pady="0")
        button_out.configure(relief="ridge")
        button_out.configure(text='''Scan Out''')

        entry_addShopList = tk.Entry(canvas_base)
        entry_addShopList.place(relx=0.039, rely=0.933, height=20
                , relwidth=0.248)
        entry_addShopList.configure(background="white")
        entry_addShopList.configure(disabledforeground="#a3a3a3")
        entry_addShopList.configure(font="TkFixedFont")
        entry_addShopList.configure(foreground="#000000")
        entry_addShopList.configure(highlightbackground="#d9d9d9")
        entry_addShopList.configure(highlightcolor="black")
        entry_addShopList.configure(insertbackground="black")
        entry_addShopList.configure(selectbackground="blue")
        entry_addShopList.configure(selectforeground="white")

        button_addShopList = tk.Button(canvas_base)
        button_addShopList.place(relx=0.303, rely=0.933, height=24
                , width=200)
        button_addShopList.configure(activebackground="#ececec")
        button_addShopList.configure(activeforeground="#000000")
        button_addShopList.configure(background="#d9d9d9")
        button_addShopList.configure(disabledforeground="#a3a3a3")
        button_addShopList.configure(foreground="#000000")
        button_addShopList.configure(highlightbackground="#d9d9d9")
        button_addShopList.configure(highlightcolor="black")
        button_addShopList.configure(pady="0")
        button_addShopList.configure(text='''Add To Shopping List''')

        frame_invMain = tk.Frame(canvas_base)
        frame_invMain.place(relx=0.0, rely=0.167, relheight=0.75
                , relwidth=1.0)
        frame_invMain.configure(relief='groove')
        frame_invMain.configure(borderwidth="2")
        frame_invMain.configure(relief="groove")
        frame_invMain.configure(background="#585670")
        frame_invMain.configure(highlightbackground="#d9d9d9")
        frame_invMain.configure(highlightcolor="black")

        label_inv_name = tk.Label(frame_invMain)
        label_inv_name.place(relx=0.127, rely=0.044, height=30, width=125)
        label_inv_name.configure(activebackground="#f9f9f9")
        label_inv_name.configure(activeforeground="black")
        label_inv_name.configure(background="#939393")
        label_inv_name.configure(disabledforeground="#a3a3a3")
        label_inv_name.configure(foreground="#000000")
        label_inv_name.configure(highlightbackground="#d9d9d9")
        label_inv_name.configure(highlightcolor="black")
        label_inv_name.configure(text='''Name''')

        label_inv_quan = tk.Label(frame_invMain)
        label_inv_quan.place(relx=0.264, rely=0.044, height=30, width=125)
        label_inv_quan.configure(activebackground="#f9f9f9")
        label_inv_quan.configure(activeforeground="black")
        label_inv_quan.configure(background="#939393")
        label_inv_quan.configure(disabledforeground="#a3a3a3")
        label_inv_quan.configure(foreground="#000000")
        label_inv_quan.configure(highlightbackground="#d9d9d9")
        label_inv_quan.configure(highlightcolor="black")
        label_inv_quan.configure(text='''Quantity''')

        label_inv_fg = tk.Label(frame_invMain)
        label_inv_fg.place(relx=0.4, rely=0.044, height=30, width=125)
        label_inv_fg.configure(activebackground="#f9f9f9")
        label_inv_fg.configure(activeforeground="black")
        label_inv_fg.configure(background="#939393")
        label_inv_fg.configure(disabledforeground="#a3a3a3")
        label_inv_fg.configure(foreground="#000000")
        label_inv_fg.configure(highlightbackground="#d9d9d9")
        label_inv_fg.configure(highlightcolor="black")
        label_inv_fg.configure(text='''Food Group''')

        label_inv_end = tk.Label(frame_invMain)
        label_inv_end.place(relx=0.537, rely=0.044, height=30, width=125)
        label_inv_end.configure(activebackground="#f9f9f9")
        label_inv_end.configure(activeforeground="black")
        label_inv_end.configure(background="#939393")
        label_inv_end.configure(disabledforeground="#a3a3a3")
        label_inv_end.configure(foreground="#000000")
        label_inv_end.configure(highlightbackground="#d9d9d9")
        label_inv_end.configure(highlightcolor="black")
        label_inv_end.configure(text='''Entry Date''')

        label_inv_exd = tk.Label(frame_invMain)
        label_inv_exd.place(relx=0.674, rely=0.044, height=30, width=125)
        label_inv_exd.configure(activebackground="#f9f9f9")
        label_inv_exd.configure(activeforeground="black")
        label_inv_exd.configure(background="#939393")
        label_inv_exd.configure(disabledforeground="#a3a3a3")
        label_inv_exd.configure(foreground="#000000")
        label_inv_exd.configure(highlightbackground="#d9d9d9")
        label_inv_exd.configure(highlightcolor="black")
        label_inv_exd.configure(text='''Exp. Date''')

        label_inv_bar = tk.Label(frame_invMain)
        label_inv_bar.place(relx=0.811, rely=0.044, height=30, width=125)
        label_inv_bar.configure(activebackground="#f9f9f9")
        label_inv_bar.configure(activeforeground="black")
        label_inv_bar.configure(background="#939393")
        label_inv_bar.configure(disabledforeground="#a3a3a3")
        label_inv_bar.configure(foreground="#000000")
        label_inv_bar.configure(highlightbackground="#d9d9d9")
        label_inv_bar.configure(highlightcolor="black")
        label_inv_bar.configure(text='''Barcode''')

        button_inv_del = tk.Button(frame_invMain)
        button_inv_del.place(relx=0.049, rely=0.044, height=24, width=47)
        button_inv_del.configure(activebackground="#ececec")
        button_inv_del.configure(activeforeground="#000000")
        button_inv_del.configure(background="#af0101")
        button_inv_del.configure(disabledforeground="#a3a3a3")
        button_inv_del.configure(foreground="#000000")
        button_inv_del.configure(highlightbackground="#d9d9d9")
        button_inv_del.configure(highlightcolor="black")
        button_inv_del.configure(pady="0")
        button_inv_del.configure(text='''Delete''')

        button_inv_nameAct = tk.Button(frame_invMain)
        button_inv_nameAct.place(relx=0.127, rely=0.156, height=30
                , width=125)
        button_inv_nameAct.configure(activebackground="#ececec")
        button_inv_nameAct.configure(activeforeground="#000000")
        button_inv_nameAct.configure(background="#d3d3d3")
        button_inv_nameAct.configure(disabledforeground="#a3a3a3")
        button_inv_nameAct.configure(foreground="#000000")
        button_inv_nameAct.configure(highlightbackground="#d9d9d9")
        button_inv_nameAct.configure(highlightcolor="black")
        button_inv_nameAct.configure(pady="0")
        button_inv_nameAct.configure(relief="flat")
        button_inv_nameAct.configure(text='''NAME BUTTON''')

        Checkbutton1 = tk.Checkbutton(frame_invMain)
        Checkbutton1.place(relx=0.049, rely=0.156, relheight=0.056
                , relwidth=0.061)
        Checkbutton1.configure(activebackground="#ececec")
        Checkbutton1.configure(activeforeground="#000000")
        Checkbutton1.configure(background="#585670")
        Checkbutton1.configure(disabledforeground="#a3a3a3")
        Checkbutton1.configure(foreground="#000000")
        Checkbutton1.configure(highlightbackground="#d9d9d9")
        Checkbutton1.configure(highlightcolor="black")
        Checkbutton1.configure(justify='left')
        Checkbutton1.configure(variable=Inventory_support.che72)

        label_inv_quanData = tk.Label(frame_invMain)
        label_inv_quanData.place(relx=0.264, rely=0.156, height=30
                , width=124)
        label_inv_quanData.configure(activebackground="#f9f9f9")
        label_inv_quanData.configure(activeforeground="black")
        label_inv_quanData.configure(background="#d9d9d9")
        label_inv_quanData.configure(disabledforeground="#a3a3a3")
        label_inv_quanData.configure(foreground="#000000")
        label_inv_quanData.configure(highlightbackground="#d9d9d9")
        label_inv_quanData.configure(highlightcolor="black")
        label_inv_quanData.configure(text='''X''')

        label_inv_fgData = tk.Label(frame_invMain)
        label_inv_fgData.place(relx=0.4, rely=0.156, height=30, width=125)
        label_inv_fgData.configure(activebackground="#f9f9f9")
        label_inv_fgData.configure(activeforeground="black")
        label_inv_fgData.configure(background="#d9d9d9")
        label_inv_fgData.configure(disabledforeground="#a3a3a3")
        label_inv_fgData.configure(foreground="#000000")
        label_inv_fgData.configure(highlightbackground="#d9d9d9")
        label_inv_fgData.configure(highlightcolor="black")
        label_inv_fgData.configure(text='''X''')

        label_inv_endData = tk.Label(frame_invMain)
        label_inv_endData.place(relx=0.537, rely=0.156, height=30
                , width=125)
        label_inv_endData.configure(activebackground="#f9f9f9")
        label_inv_endData.configure(activeforeground="black")
        label_inv_endData.configure(background="#d9d9d9")
        label_inv_endData.configure(disabledforeground="#a3a3a3")
        label_inv_endData.configure(foreground="#000000")
        label_inv_endData.configure(highlightbackground="#d9d9d9")
        label_inv_endData.configure(highlightcolor="black")
        label_inv_endData.configure(text='''X''')

        label_inv_exdData = tk.Label(frame_invMain)
        label_inv_exdData.place(relx=0.674, rely=0.156, height=30
                , width=125)
        label_inv_exdData.configure(activebackground="#f9f9f9")
        label_inv_exdData.configure(activeforeground="black")
        label_inv_exdData.configure(background="#d9d9d9")
        label_inv_exdData.configure(disabledforeground="#a3a3a3")
        label_inv_exdData.configure(foreground="#000000")
        label_inv_exdData.configure(highlightbackground="#d9d9d9")
        label_inv_exdData.configure(highlightcolor="black")
        label_inv_exdData.configure(text='''X''')

        label_inv_barcData = tk.Label(frame_invMain)
        label_inv_barcData.place(relx=0.811, rely=0.156, height=30
                , width=125)
        label_inv_barcData.configure(activebackground="#f9f9f9")
        label_inv_barcData.configure(activeforeground="black")
        label_inv_barcData.configure(background="#d9d9d9")
        label_inv_barcData.configure(disabledforeground="#a3a3a3")
        label_inv_barcData.configure(foreground="#000000")
        label_inv_barcData.configure(highlightbackground="#d9d9d9")
        label_inv_barcData.configure(highlightcolor="black")
        label_inv_barcData.configure(text='''X''')

        Button1 = tk.Button(frame_invMain)
        Button1.place(relx=0.947, rely=0.889, height=40, width=45)
        Button1.configure(activebackground="#ececec")
        Button1.configure(activeforeground="#000000")
        Button1.configure(background="#d9d9d9")
        Button1.configure(disabledforeground="#a3a3a3")
        Button1.configure(foreground="#000000")
        Button1.configure(highlightbackground="#d9d9d9")
        Button1.configure(highlightcolor="black")
        Button1.configure(pady="0")
        Button1.configure(text='''>>''')

        Button2 = tk.Button(frame_invMain)
        Button2.place(relx=0.01, rely=0.889, height=40, width=45)
        Button2.configure(activebackground="#ececec")
        Button2.configure(activeforeground="#000000")
        Button2.configure(background="#d9d9d9")
        Button2.configure(disabledforeground="#a3a3a3")
        Button2.configure(foreground="#000000")
        Button2.configure(highlightbackground="#d9d9d9")
        Button2.configure(highlightcolor="black")
        Button2.configure(pady="0")
        Button2.configure(text='''<<''')

        frame_inv_search = tk.Frame(canvas_base)
        frame_inv_search.place(relx=0.0, rely=0.083, relheight=0.083
                , relwidth=1.0)
        frame_inv_search.configure(relief='groove')
        frame_inv_search.configure(borderwidth="2")
        frame_inv_search.configure(relief="groove")
        frame_inv_search.configure(background="#737373")
        frame_inv_search.configure(highlightbackground="#d9d9d9")
        frame_inv_search.configure(highlightcolor="black")

        entry_inv_search = tk.Entry(frame_inv_search)
        entry_inv_search.place(relx=0.02, rely=0.3, height=20
                , relwidth=0.17)
        entry_inv_search.configure(background="white")
        entry_inv_search.configure(disabledforeground="#a3a3a3")
        entry_inv_search.configure(font="TkFixedFont")
        entry_inv_search.configure(foreground="#000000")
        entry_inv_search.configure(highlightbackground="#d9d9d9")
        entry_inv_search.configure(highlightcolor="black")
        entry_inv_search.configure(insertbackground="black")
        entry_inv_search.configure(selectbackground="blue")
        entry_inv_search.configure(selectforeground="white")

        button_inv_search = tk.Button(frame_inv_search)
        button_inv_search.place(relx=0.205, rely=0.3, height=24, width=47)
        button_inv_search.configure(activebackground="#ececec")
        button_inv_search.configure(activeforeground="#000000")
        button_inv_search.configure(background="#d9d9d9")
        button_inv_search.configure(disabledforeground="#a3a3a3")
        button_inv_search.configure(foreground="#000000")
        button_inv_search.configure(highlightbackground="#d9d9d9")
        button_inv_search.configure(highlightcolor="black")
        button_inv_search.configure(pady="0")
        button_inv_search.configure(text='''Search''')

        combo_inv_type = ttk.Combobox(frame_inv_search)
        combo_inv_type.place(relx=0.508, rely=0.3, relheight=0.42
                , relwidth=0.146)
        combo_inv_type.configure(textvariable=Inventory_support.combobox)
        combo_inv_type.configure(takefocus="")

        combo_inv_crit = ttk.Combobox(frame_inv_search)
        combo_inv_crit.place(relx=0.664, rely=0.3, relheight=0.42
                , relwidth=0.14)
        combo_inv_crit.configure(textvariable=Inventory_support.combobox)
        combo_inv_crit.configure(takefocus="")

        button_inv_filter = tk.Button(frame_inv_search)
        button_inv_filter.place(relx=0.82, rely=0.3, height=24, width=70)
        button_inv_filter.configure(activebackground="#ececec")
        button_inv_filter.configure(activeforeground="#000000")
        button_inv_filter.configure(background="#d9d9d9")
        button_inv_filter.configure(disabledforeground="#a3a3a3")
        button_inv_filter.configure(foreground="#000000")
        button_inv_filter.configure(highlightbackground="#d9d9d9")
        button_inv_filter.configure(highlightcolor="black")
        button_inv_filter.configure(pady="0")
        button_inv_filter.configure(text='''Filter''')

        button_inv_CLfilter = tk.Button(frame_inv_search)
        button_inv_CLfilter.place(relx=0.908, rely=0.3, height=24, width=70)

        button_inv_CLfilter.configure(activebackground="#ececec")
        button_inv_CLfilter.configure(activeforeground="#000000")
        button_inv_CLfilter.configure(background="#d9d9d9")
        button_inv_CLfilter.configure(disabledforeground="#a3a3a3")
        button_inv_CLfilter.configure(foreground="#000000")
        button_inv_CLfilter.configure(highlightbackground="#d9d9d9")
        button_inv_CLfilter.configure(highlightcolor="black")
        button_inv_CLfilter.configure(pady="0")
        button_inv_CLfilter.configure(text='''Clear Filter''')

if __name__ == '__main__':
    vp_start_gui()
