#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.6
#  in conjunction with Tcl version 8.6
#    Nov 23, 2020 12:00:53 AM EST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import ShoppingList_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    ShoppingList_support.set_Tk_var()
    root = Toplevel1 (root)
    ShoppingList_support.init(root, root)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    ShoppingList_support.set_Tk_var()
    root = Toplevel1 (w)
    ShoppingList_support.init(w, root, *args, **kwargs)
    return (w, root)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, root=None):
        '''This class configures and populates the rootlevel window.
           root is the rootlevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        root.geometry("1173x873+319+95")
        root.minsize(120, 1)
        root.maxsize(1924, 1061)
        root.resizable(1,  1)
        root.title("New Toplevel")
        root.configure(background="#d9d9d9")
        root.configure(highlightbackground="#d9d9d9")
        root.configure(highlightcolor="black")

        canvas_base = tk.Canvas(root)
        canvas_base.place(relx=0.06, rely=0.126, relheight=0.687
                , relwidth=0.873)
        canvas_base.configure(background="#3e3c55")
        canvas_base.configure(borderwidth="2")
        canvas_base.configure(highlightbackground="#d9d9d9")
        canvas_base.configure(highlightcolor="black")
        canvas_base.configure(insertbackground="black")
        canvas_base.configure(relief="ridge")
        canvas_base.configure(selectbackground="blue")
        canvas_base.configure(selectforeground="white")

        button_Inventory = tk.Button(canvas_base)
        button_Inventory.place(relx=0.0, rely=0.0, height=50, width=341)
        button_Inventory.configure(activebackground="#ececec")
        button_Inventory.configure(activeforeground="#000000")
        button_Inventory.configure(background="#d9d9d9")
        button_Inventory.configure(disabledforeground="#a3a3a3")
        button_Inventory.configure(foreground="#000000")
        button_Inventory.configure(highlightbackground="#d9d9d9")
        button_Inventory.configure(highlightcolor="black")
        button_Inventory.configure(pady="0")
        button_Inventory.configure(relief="ridge")
        button_Inventory.configure(text='''Inventory''')

        button_shoplist = tk.Button(canvas_base)
        button_shoplist.place(relx=0.332, rely=0.0, height=50, width=342)
        button_shoplist.configure(activebackground="#ececec")
        button_shoplist.configure(activeforeground="#000000")
        button_shoplist.configure(background="#d9d9d9")
        button_shoplist.configure(disabledforeground="#a3a3a3")
        button_shoplist.configure(foreground="#000000")
        button_shoplist.configure(highlightbackground="#d9d9d9")
        button_shoplist.configure(highlightcolor="black")
        button_shoplist.configure(pady="0")
        button_shoplist.configure(relief="ridge")
        button_shoplist.configure(text='''Shopping List''')

        button_recipies = tk.Button(canvas_base)
        button_recipies.place(relx=0.664, rely=0.0, height=50, width=341)
        button_recipies.configure(activebackground="#ececec")
        button_recipies.configure(activeforeground="#000000")
        button_recipies.configure(background="#d9d9d9")
        button_recipies.configure(disabledforeground="#a3a3a3")
        button_recipies.configure(foreground="#000000")
        button_recipies.configure(highlightbackground="#d9d9d9")
        button_recipies.configure(highlightcolor="black")
        button_recipies.configure(pady="0")
        button_recipies.configure(relief="ridge")
        button_recipies.configure(text='''Recipies''')

        entry_barcode = tk.Entry(canvas_base)
        entry_barcode.place(relx=0.801, rely=0.933, height=20
                , relwidth=0.082)
        entry_barcode.configure(background="white")
        entry_barcode.configure(disabledforeground="#a3a3a3")
        entry_barcode.configure(font="TkFixedFont")
        entry_barcode.configure(foreground="#000000")
        entry_barcode.configure(highlightbackground="#d9d9d9")
        entry_barcode.configure(highlightcolor="black")
        entry_barcode.configure(insertbackground="black")
        entry_barcode.configure(selectbackground="blue")
        entry_barcode.configure(selectforeground="white")

        button_in = tk.Button(canvas_base)
        button_in.place(relx=0.802, rely=0.917, height=50, width=100)
        button_in.configure(activebackground="#ececec")
        button_in.configure(activeforeground="#000000")
        button_in.configure(background="#36a35c")
        button_in.configure(disabledforeground="#a3a3a3")
        button_in.configure(foreground="#000000")
        button_in.configure(highlightbackground="#d9d9d9")
        button_in.configure(highlightcolor="black")
        button_in.configure(pady="0")
        button_in.configure(text='''Scan In''')

        button_out = tk.Button(canvas_base)
        button_out.place(relx=0.899, rely=0.917, height=50, width=100)
        button_out.configure(activebackground="#ececec")
        button_out.configure(activeforeground="#000000")
        button_out.configure(background="#af0101")
        button_out.configure(disabledforeground="#a3a3a3")
        button_out.configure(foreground="#000000")
        button_out.configure(highlightbackground="#d9d9d9")
        button_out.configure(highlightcolor="black")
        button_out.configure(pady="0")
        button_out.configure(text='''Scan Out''')

        entry_addShopList = tk.Entry(canvas_base)
        entry_addShopList.place(relx=0.039, rely=0.933, height=20
                , relwidth=0.248)
        entry_addShopList.configure(background="white")
        entry_addShopList.configure(disabledforeground="#a3a3a3")
        entry_addShopList.configure(font="TkFixedFont")
        entry_addShopList.configure(foreground="#000000")
        entry_addShopList.configure(highlightbackground="#d9d9d9")
        entry_addShopList.configure(highlightcolor="black")
        entry_addShopList.configure(insertbackground="black")
        entry_addShopList.configure(selectbackground="blue")
        entry_addShopList.configure(selectforeground="white")

        button_addShopList = tk.Button(canvas_base)
        button_addShopList.place(relx=0.303, rely=0.933, height=24
                , width=200)
        button_addShopList.configure(activebackground="#ececec")
        button_addShopList.configure(activeforeground="#000000")
        button_addShopList.configure(background="#d9d9d9")
        button_addShopList.configure(disabledforeground="#a3a3a3")
        button_addShopList.configure(foreground="#000000")
        button_addShopList.configure(highlightbackground="#d9d9d9")
        button_addShopList.configure(highlightcolor="black")
        button_addShopList.configure(pady="0")
        button_addShopList.configure(text='''Add To Shopping List''')

        frame_sl_main = tk.Frame(canvas_base)
        frame_sl_main.place(relx=0.0, rely=0.083, relheight=0.833
                , relwidth=1.0)
        frame_sl_main.configure(relief='groove')
        frame_sl_main.configure(borderwidth="2")
        frame_sl_main.configure(relief="groove")
        frame_sl_main.configure(background="#585670")
        frame_sl_main.configure(highlightbackground="#d9d9d9")
        frame_sl_main.configure(highlightcolor="black")

        button_sl_delete = tk.Button(frame_sl_main)
        button_sl_delete.place(relx=0.059, rely=0.04, height=34, width=127)
        button_sl_delete.configure(activebackground="#ececec")
        button_sl_delete.configure(activeforeground="#000000")
        button_sl_delete.configure(background="#af0101")
        button_sl_delete.configure(disabledforeground="#a3a3a3")
        button_sl_delete.configure(foreground="#000000")
        button_sl_delete.configure(highlightbackground="#d9d9d9")
        button_sl_delete.configure(highlightcolor="black")
        button_sl_delete.configure(pady="0")
        button_sl_delete.configure(text='''Clear List''')

        label_sl_item = tk.Label(frame_sl_main)
        label_sl_item.place(relx=0.117, rely=0.156, height=34, width=198)
        label_sl_item.configure(activebackground="#f9f9f9")
        label_sl_item.configure(activeforeground="black")
        label_sl_item.configure(background="#d9d9d9")
        label_sl_item.configure(disabledforeground="#a3a3a3")
        label_sl_item.configure(foreground="#000000")
        label_sl_item.configure(highlightbackground="#d9d9d9")
        label_sl_item.configure(highlightcolor="black")
        label_sl_item.configure(text='''X''')

        Checkbutton2 = tk.Checkbutton(frame_sl_main)
        Checkbutton2.place(relx=0.059, rely=0.156, relheight=0.056
                , relwidth=0.061)
        Checkbutton2.configure(activebackground="#ececec")
        Checkbutton2.configure(activeforeground="#000000")
        Checkbutton2.configure(background="#585670")
        Checkbutton2.configure(disabledforeground="#a3a3a3")
        Checkbutton2.configure(foreground="#000000")
        Checkbutton2.configure(highlightbackground="#d9d9d9")
        Checkbutton2.configure(highlightcolor="black")
        Checkbutton2.configure(justify='left')
        Checkbutton2.configure(variable=ShoppingList_support.che84)

if __name__ == '__main__':
    vp_start_gui()
