#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.6
#  in conjunction with Tcl version 8.6
#    Nov 29, 2020 03:22:16 PM EST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import SLpopup_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    SLpopup_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    SLpopup_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("1173x873+302+80")
        top.minsize(120, 1)
        top.maxsize(1924, 1061)
        top.resizable(1,  1)
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.canvas_base = tk.Canvas(top)
        self.canvas_base.place(relx=0.06, rely=0.126, relheight=0.687
                , relwidth=0.873)
        self.canvas_base.configure(background="#3e3c55")
        self.canvas_base.configure(borderwidth="2")
        self.canvas_base.configure(highlightbackground="#d9d9d9")
        self.canvas_base.configure(highlightcolor="black")
        self.canvas_base.configure(insertbackground="black")
        self.canvas_base.configure(relief="ridge")
        self.canvas_base.configure(selectbackground="blue")
        self.canvas_base.configure(selectforeground="white")

        self.button_Inventory = tk.Button(self.canvas_base)
        self.button_Inventory.place(relx=0.0, rely=0.0, height=50, width=341)
        self.button_Inventory.configure(activebackground="#ececec")
        self.button_Inventory.configure(activeforeground="#000000")
        self.button_Inventory.configure(background="#d9d9d9")
        self.button_Inventory.configure(disabledforeground="#a3a3a3")
        self.button_Inventory.configure(foreground="#000000")
        self.button_Inventory.configure(highlightbackground="#d9d9d9")
        self.button_Inventory.configure(highlightcolor="black")
        self.button_Inventory.configure(pady="0")
        self.button_Inventory.configure(relief="ridge")
        self.button_Inventory.configure(text='''Inventory''')

        self.button_shoplist = tk.Button(self.canvas_base)
        self.button_shoplist.place(relx=0.332, rely=0.0, height=50, width=342)
        self.button_shoplist.configure(activebackground="#ececec")
        self.button_shoplist.configure(activeforeground="#000000")
        self.button_shoplist.configure(background="#d9d9d9")
        self.button_shoplist.configure(disabledforeground="#a3a3a3")
        self.button_shoplist.configure(foreground="#000000")
        self.button_shoplist.configure(highlightbackground="#d9d9d9")
        self.button_shoplist.configure(highlightcolor="black")
        self.button_shoplist.configure(pady="0")
        self.button_shoplist.configure(relief="ridge")
        self.button_shoplist.configure(text='''Shopping List''')

        self.button_recipies = tk.Button(self.canvas_base)
        self.button_recipies.place(relx=0.664, rely=0.0, height=50, width=341)
        self.button_recipies.configure(activebackground="#ececec")
        self.button_recipies.configure(activeforeground="#000000")
        self.button_recipies.configure(background="#d9d9d9")
        self.button_recipies.configure(disabledforeground="#a3a3a3")
        self.button_recipies.configure(foreground="#000000")
        self.button_recipies.configure(highlightbackground="#d9d9d9")
        self.button_recipies.configure(highlightcolor="black")
        self.button_recipies.configure(pady="0")
        self.button_recipies.configure(relief="ridge")
        self.button_recipies.configure(text='''Recipies''')

        self.entry_barcode = tk.Entry(self.canvas_base)
        self.entry_barcode.place(relx=0.811, rely=0.933, height=20
                , relwidth=0.082)
        self.entry_barcode.configure(background="white")
        self.entry_barcode.configure(disabledforeground="#a3a3a3")
        self.entry_barcode.configure(font="TkFixedFont")
        self.entry_barcode.configure(foreground="#000000")
        self.entry_barcode.configure(highlightbackground="#d9d9d9")
        self.entry_barcode.configure(highlightcolor="black")
        self.entry_barcode.configure(insertbackground="black")
        self.entry_barcode.configure(selectbackground="blue")
        self.entry_barcode.configure(selectforeground="white")

        self.button_in = tk.Button(self.canvas_base)
        self.button_in.place(relx=0.801, rely=0.917, height=50, width=100)
        self.button_in.configure(activebackground="#ececec")
        self.button_in.configure(activeforeground="#000000")
        self.button_in.configure(background="#36a35c")
        self.button_in.configure(disabledforeground="#a3a3a3")
        self.button_in.configure(foreground="#000000")
        self.button_in.configure(highlightbackground="#d9d9d9")
        self.button_in.configure(highlightcolor="black")
        self.button_in.configure(pady="0")
        self.button_in.configure(text='''Scan In''')

        self.button_out = tk.Button(self.canvas_base)
        self.button_out.place(relx=0.899, rely=0.917, height=50, width=100)
        self.button_out.configure(activebackground="#ececec")
        self.button_out.configure(activeforeground="#000000")
        self.button_out.configure(background="#af0101")
        self.button_out.configure(disabledforeground="#a3a3a3")
        self.button_out.configure(foreground="#000000")
        self.button_out.configure(highlightbackground="#d9d9d9")
        self.button_out.configure(highlightcolor="black")
        self.button_out.configure(pady="0")
        self.button_out.configure(text='''Scan Out''')

        self.entry_addShopList = tk.Entry(self.canvas_base)
        self.entry_addShopList.place(relx=0.039, rely=0.933, height=20
                , relwidth=0.248)
        self.entry_addShopList.configure(background="white")
        self.entry_addShopList.configure(disabledforeground="#a3a3a3")
        self.entry_addShopList.configure(font="TkFixedFont")
        self.entry_addShopList.configure(foreground="#000000")
        self.entry_addShopList.configure(highlightbackground="#d9d9d9")
        self.entry_addShopList.configure(highlightcolor="black")
        self.entry_addShopList.configure(insertbackground="black")
        self.entry_addShopList.configure(selectbackground="blue")
        self.entry_addShopList.configure(selectforeground="white")

        self.button_addShopList = tk.Button(self.canvas_base)
        self.button_addShopList.place(relx=0.303, rely=0.933, height=24
                , width=200)
        self.button_addShopList.configure(activebackground="#ececec")
        self.button_addShopList.configure(activeforeground="#000000")
        self.button_addShopList.configure(background="#d9d9d9")
        self.button_addShopList.configure(disabledforeground="#a3a3a3")
        self.button_addShopList.configure(foreground="#000000")
        self.button_addShopList.configure(highlightbackground="#d9d9d9")
        self.button_addShopList.configure(highlightcolor="black")
        self.button_addShopList.configure(pady="0")
        self.button_addShopList.configure(text='''Add To Shopping List''')

        self.Frame1 = tk.Frame(self.canvas_base)
        self.Frame1.place(relx=0.371, rely=0.183, relheight=0.408
                , relwidth=0.271)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#d9d9d9")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")

        self.button_delete = tk.Button(self.Frame1)
        self.button_delete.place(relx=0.181, rely=0.833, height=24, width=175)
        self.button_delete.configure(activebackground="#ececec")
        self.button_delete.configure(activeforeground="#000000")
        self.button_delete.configure(background="#d9d9d9")
        self.button_delete.configure(disabledforeground="#a3a3a3")
        self.button_delete.configure(foreground="#000000")
        self.button_delete.configure(highlightbackground="#d9d9d9")
        self.button_delete.configure(highlightcolor="black")
        self.button_delete.configure(pady="0")
        self.button_delete.configure(text='''Remove From Shopping List''')

        self.label_sld_name = tk.Label(self.Frame1)
        self.label_sld_name.place(relx=0.144, rely=0.155, height=16, width=200)
        self.label_sld_name.configure(activebackground="#f9f9f9")
        self.label_sld_name.configure(activeforeground="black")
        self.label_sld_name.configure(background="#d9d9d9")
        self.label_sld_name.configure(disabledforeground="#a3a3a3")
        self.label_sld_name.configure(foreground="#000000")
        self.label_sld_name.configure(highlightbackground="#d9d9d9")
        self.label_sld_name.configure(highlightcolor="black")
        self.label_sld_name.configure(justify='left')
        self.label_sld_name.configure(text='''Name''')

        self.label_sld_n = tk.Label(self.Frame1)
        self.label_sld_n.place(relx=0.144, rely=0.245, height=16, width=200)
        self.label_sld_n.configure(activebackground="#f9f9f9")
        self.label_sld_n.configure(activeforeground="black")
        self.label_sld_n.configure(background="#d9d9d9")
        self.label_sld_n.configure(disabledforeground="#a3a3a3")
        self.label_sld_n.configure(foreground="#000000")
        self.label_sld_n.configure(highlightbackground="#d9d9d9")
        self.label_sld_n.configure(highlightcolor="black")
        self.label_sld_n.configure(justify='left')
        self.label_sld_n.configure(text='''Notes:''')

        self.label_sld_notes = tk.Label(self.Frame1)
        self.label_sld_notes.place(relx=0.144, rely=0.327, height=16, width=200)
        self.label_sld_notes.configure(activebackground="#f9f9f9")
        self.label_sld_notes.configure(activeforeground="black")
        self.label_sld_notes.configure(background="#d9d9d9")
        self.label_sld_notes.configure(disabledforeground="#a3a3a3")
        self.label_sld_notes.configure(foreground="#000000")
        self.label_sld_notes.configure(highlightbackground="#d9d9d9")
        self.label_sld_notes.configure(highlightcolor="black")
        self.label_sld_notes.configure(justify='left')
        self.label_sld_notes.configure(text='''X''')

        self.button_closeDel = tk.Button(self.Frame1)
        self.button_closeDel.place(relx=0.884, rely=0.033, height=25, width=25)
        self.button_closeDel.configure(activebackground="#ececec")
        self.button_closeDel.configure(activeforeground="#000000")
        self.button_closeDel.configure(background="#acacac")
        self.button_closeDel.configure(disabledforeground="#a3a3a3")
        self.button_closeDel.configure(foreground="#000000")
        self.button_closeDel.configure(highlightbackground="#d9d9d9")
        self.button_closeDel.configure(highlightcolor="black")
        self.button_closeDel.configure(pady="0")
        self.button_closeDel.configure(text='''X''')

if __name__ == '__main__':
    vp_start_gui()





