#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.6
#  in conjunction with Tcl version 8.6
#    Nov 01, 2020 12:45:04 PM EST  platform: Windows NT
import tkinter as tk
#import ttk
#import UI_mainscreen_support

def vp_start_gui():
     '''Starting point when module is the main routine.'''
     global val, w, root
     root = tk.Tk()
     UI_mainscreen_support.set_Tk_var()
     top = Toplevel1 (root)
     UI_mainscreen_support.init(root, top)
     root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
     '''Starting point when module is imported by another module.
        Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
     global w, w_win, root
     #rt = root
     root = rt
     w = tk.Toplevel (root)
     UI_mainscreen_support.set_Tk_var()
     top = Toplevel1 (w)
     UI_mainscreen_support.init(w, top, *args, **kwargs)
     return (w, top)

def destroy_Toplevel1():
     global w
     w.destroy()
     w = None

class Toplevel1:
    def __init__(self, top=None):
         '''This class configures and populates the toplevel window.
            top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
         _fgcolor = '#000000'  # X11 color: 'black'
         _compcolor = '#d9d9d9' # X11 color: 'gray85'
         _ana1color = '#d9d9d9' # X11 color: 'gray85'
         _ana2color = '#ececec' # Closest X11 color: 'gray92'

         top.geometry("1308x776+269+115")
         top.minsize(120, 1)
         top.maxsize(3844, 1061)
         top.resizable(1,  1)
         top.title("New Toplevel")
         top.configure(background="#d9d9d9")

         Canvas1 = tk.Canvas(top)
         Canvas1.place(relx=0.008, rely=0.09, relheight=0.773
                 , relwidth=0.784)
         Canvas1.configure(background="#d9d9d9")
         Canvas1.configure(borderwidth="2")
         Canvas1.configure(insertbackground="black")
         Canvas1.configure(relief="ridge")
         Canvas1.configure(selectbackground="blue")
         Canvas1.configure(selectforeground="white")

         inventory = tk.Button(Canvas1)
         inventory.place(relx=0.0, rely=0.0, height=80, width=341)
         inventory.configure(activebackground="#ececec")
         inventory.configure(activeforeground="#000000")
         inventory.configure(background="#d9d9d9")
         inventory.configure(disabledforeground="#a3a3a3")
         inventory.configure(foreground="#000000")
         inventory.configure(highlightbackground="#d9d9d9")
         inventory.configure(highlightcolor="black")
         inventory.configure(pady="0")
         inventory.configure(relief="groove")
         inventory.configure(text='''Inventory''')

         shoplist = tk.Button(Canvas1)
         shoplist.place(relx=0.331, rely=0.0, height=80, width=342)
         shoplist.configure(activebackground="#ececec")
         shoplist.configure(activeforeground="#000000")
         shoplist.configure(background="#d9d9d9")
         shoplist.configure(disabledforeground="#a3a3a3")
         shoplist.configure(foreground="#000000")
         shoplist.configure(highlightbackground="#d9d9d9")
         shoplist.configure(highlightcolor="black")
         shoplist.configure(pady="0")
         shoplist.configure(relief="groove")
         shoplist.configure(text='''Shopping List''')

         recipies = tk.Button(Canvas1)
         recipies.place(relx=0.663, rely=0.0, height=80, width=341)
         recipies.configure(activebackground="#ececec")
         recipies.configure(activeforeground="#000000")
         recipies.configure(background="#d9d9d9")
         recipies.configure(disabledforeground="#a3a3a3")
         recipies.configure(foreground="#000000")
         recipies.configure(highlightbackground="#d9d9d9")
         recipies.configure(highlightcolor="black")
         recipies.configure(pady="0")
         recipies.configure(relief="groove")
         recipies.configure(text='''Recipies''')

         scan_out = tk.Button(Canvas1)
         scan_out.place(relx=0.897, rely=0.867, height=80, width=100)
         scan_out.configure(activebackground="#ececec")
         scan_out.configure(activeforeground="#000000")
         scan_out.configure(background="#cd0532")
         scan_out.configure(disabledforeground="#a3a3a3")
         scan_out.configure(foreground="#000000")
         scan_out.configure(highlightbackground="#d9d9d9")
         scan_out.configure(highlightcolor="black")
         scan_out.configure(pady="0")
         scan_out.configure(relief="groove")
         scan_out.configure(text='''Scan Out''')

         add_list = tk.Button(Canvas1)
         add_list.place(relx=0.195, rely=0.917, height=24, width=150)
         add_list.configure(activebackground="#ececec")
         add_list.configure(activeforeground="#000000")
         add_list.configure(background="#d9d9d9")
         add_list.configure(disabledforeground="#a3a3a3")
         add_list.configure(foreground="#000000")
         add_list.configure(highlightbackground="#d9d9d9")
         add_list.configure(highlightcolor="black")
         add_list.configure(pady="0")
         add_list.configure(text='''Add To Shopping List''')

         addlist_entry = tk.Entry(Canvas1)
         addlist_entry.place(relx=0.029, rely=0.917, height=20
                 , relwidth=0.15)
         addlist_entry.configure(background="white")
         addlist_entry.configure(disabledforeground="#a3a3a3")
         addlist_entry.configure(font="TkFixedFont")
         addlist_entry.configure(foreground="#000000")
         addlist_entry.configure(insertbackground="black")

         Entry2 = tk.Entry(Canvas1)
         Entry2.place(relx=0.809, rely=0.917, height=20, relwidth=0.082)
         Entry2.configure(background="white")
         Entry2.configure(disabledforeground="#a3a3a3")
         Entry2.configure(font="TkFixedFont")
         Entry2.configure(foreground="#000000")
         Entry2.configure(insertbackground="black")

         scan_in = tk.Button(Canvas1)
         scan_in.place(relx=0.799, rely=0.867, height=80, width=100)
         scan_in.configure(activebackground="#ececec")
         scan_in.configure(activeforeground="#000000")
         scan_in.configure(background="#008000")
         scan_in.configure(disabledforeground="#a3a3a3")
         scan_in.configure(foreground="#000000")
         scan_in.configure(highlightbackground="#d9d9d9")
         scan_in.configure(highlightcolor="black")
         scan_in.configure(pady="0")
         scan_in.configure(text='''Scan In''')

         Frame1 = tk.Frame(Canvas1)
         Frame1.place(relx=0.0, rely=0.133, relheight=0.753, relwidth=0.997)
         Frame1.configure(relief='groove')
         Frame1.configure(borderwidth="2")
         Frame1.configure(relief="groove")
         Frame1.configure(background="#3aeded")

         inv_name_label = tk.Label(Frame1)
         inv_name_label.place(relx=0.176, rely=0.199, height=30, width=156)
         inv_name_label.configure(background="#c8f5f9")
         inv_name_label.configure(disabledforeground="#a3a3a3")
         inv_name_label.configure(foreground="#000000")
         inv_name_label.configure(text='''Name''')

         inv_qua_label = tk.Label(Frame1)
         inv_qua_label.place(relx=0.332, rely=0.199, height=30, width=155)
         inv_qua_label.configure(background="#c8f5f9")
         inv_qua_label.configure(disabledforeground="#a3a3a3")
         inv_qua_label.configure(foreground="#000000")
         inv_qua_label.configure(text='''Quantity''')

         inv_fg_label = tk.Label(Frame1)
         inv_fg_label.place(relx=0.489, rely=0.199, height=30, width=153)
         inv_fg_label.configure(background="#c8f5f9")
         inv_fg_label.configure(disabledforeground="#a3a3a3")
         inv_fg_label.configure(foreground="#000000")
         inv_fg_label.configure(text='''Food Group''')

         inv_end_label = tk.Label(Frame1)
         inv_end_label.place(relx=0.645, rely=0.199, height=30, width=150)
         inv_end_label.configure(background="#c8f5f9")
         inv_end_label.configure(disabledforeground="#a3a3a3")
         inv_end_label.configure(foreground="#000000")
         inv_end_label.configure(text='''Entry Date''')

         inv_exd_label = tk.Label(Frame1)
         inv_exd_label.place(relx=0.802, rely=0.199, height=30, width=152)
         inv_exd_label.configure(background="#c8f5f9")
         inv_exd_label.configure(disabledforeground="#a3a3a3")
         inv_exd_label.configure(foreground="#000000")
         inv_exd_label.configure(text='''Exp. Date''')

         Checkbutton1 = tk.Checkbutton(Frame1)
         Checkbutton1.place(relx=0.078, rely=0.31, relheight=0.055
                 , relwidth=0.06)
         Checkbutton1.configure(activebackground="#ececec")
         Checkbutton1.configure(activeforeground="#000000")
         Checkbutton1.configure(background="#3aeded")
         Checkbutton1.configure(disabledforeground="#a3a3a3")
         Checkbutton1.configure(foreground="#000000")
         Checkbutton1.configure(highlightbackground="#d9d9d9")
         Checkbutton1.configure(highlightcolor="black")
         Checkbutton1.configure(justify='left')
         Checkbutton1.configure(variable=UI_mainscreen_support.che63)

         iv_nameinfo_but = tk.Button(Frame1)
         iv_nameinfo_but.place(relx=0.176, rely=0.288, height=30, width=150)
         iv_nameinfo_but.configure(activebackground="#ececec")
         iv_nameinfo_but.configure(activeforeground="#000000")
         iv_nameinfo_but.configure(background="#bfecf9")
         iv_nameinfo_but.configure(disabledforeground="#a3a3a3")
         iv_nameinfo_but.configure(foreground="#000000")
         iv_nameinfo_but.configure(highlightbackground="#d9d9d9")
         iv_nameinfo_but.configure(highlightcolor="black")
         iv_nameinfo_but.configure(pady="0")
         iv_nameinfo_but.configure(relief="flat")
         iv_nameinfo_but.configure(text='''X''')

if __name__ == '__main__':
     vp_start_gui()
